erDiagram
ActionAccessSpecification {
    stringList category  
    stringList eligibleRegion  
    stringList availabilityEnds  
    stringList availabilityStarts  
    stringList ineligibleRegion  
    stringList requiresSubscription  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

ActionAccessSpecification ||--}o Offer : "expectsAcceptanceOf"
ActionAccessSpecification ||--}o Action : "potentialAction"

