erDiagram
Action {
    stringList location  
    stringList participant  
    stringList agent  
    stringList endTime  
    stringList provider  
    stringList startTime  
    stringList target  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

Action ||--}o Thing : "instrument"
Action ||--}o Thing : "object"
Action ||--}o Thing : "result"
Action ||--}o HowTo : "actionProcess"
Action ||--}o ActionStatusType : "actionStatus"
Action ||--}o Thing : "error"
Action ||--}o Text : "alternateName"
Action ||--}o Text : "disambiguatingDescription"
Action ||--}o Text : "name"
Action ||--}o URL : "sameAs"
Action ||--}o Action : "potentialAction"
Action ||--}o URL : "url"

