erDiagram
AddAction {
    stringList location  
    stringList participant  
    stringList agent  
    stringList endTime  
    stringList provider  
    stringList startTime  
    stringList target  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

AddAction ||--}o Thing : "collection"
AddAction ||--}o Thing : "targetCollection"
AddAction ||--}o Thing : "instrument"
AddAction ||--}o Thing : "object"
AddAction ||--}o Thing : "result"
AddAction ||--}o HowTo : "actionProcess"
AddAction ||--}o ActionStatusType : "actionStatus"
AddAction ||--}o Thing : "error"
AddAction ||--}o Text : "alternateName"
AddAction ||--}o Text : "disambiguatingDescription"
AddAction ||--}o Text : "name"
AddAction ||--}o URL : "sameAs"
AddAction ||--}o Action : "potentialAction"
AddAction ||--}o URL : "url"

