erDiagram
AggregateOffer {
    stringList highPrice  
    stringList lowPrice  
    IntegerList offerCount  
    stringList offers  
    stringList areaServed  
    stringList asin  
    stringList category  
    stringList eligibleRegion  
    stringList gtin  
    TextList gtin12  
    TextList gtin13  
    TextList gtin14  
    TextList gtin8  
    URLList hasGS1DigitalLink  
    stringList seller  
    TextList serialNumber  
    TextList sku  
    stringList acceptedPaymentMethod  
    stringList availabilityEnds  
    stringList availabilityStarts  
    TextList checkoutPageURLTemplate  
    stringList ineligibleRegion  
    BooleanList isFamilyFriendly  
    stringList itemOffered  
    stringList leaseLength  
    TextList mobileUrl  
    TextList mpn  
    stringList offeredBy  
    stringList price  
    TextList priceCurrency  
    DateList priceValidUntil  
    stringList validFrom  
    stringList validThrough  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

AggregateOffer ||--}o Place : "availableAtOrFrom"
AggregateOffer ||--}o Offer : "addOn"
AggregateOffer ||--}o PropertyValue : "additionalProperty"
AggregateOffer ||--}o QuantitativeValue : "advanceBookingRequirement"
AggregateOffer ||--}o AggregateRating : "aggregateRating"
AggregateOffer ||--}o ItemAvailability : "availability"
AggregateOffer ||--}o DeliveryMethod : "availableDeliveryMethod"
AggregateOffer ||--}o BusinessFunction : "businessFunction"
AggregateOffer ||--}o QuantitativeValue : "deliveryLeadTime"
AggregateOffer ||--}o BusinessEntityType : "eligibleCustomerType"
AggregateOffer ||--}o QuantitativeValue : "eligibleDuration"
AggregateOffer ||--}o QuantitativeValue : "eligibleQuantity"
AggregateOffer ||--}o PriceSpecification : "eligibleTransactionVolume"
AggregateOffer ||--}o AdultOrientedEnumeration : "hasAdultConsideration"
AggregateOffer ||--}o QuantitativeValue : "hasMeasurement"
AggregateOffer ||--}o MerchantReturnPolicy : "hasMerchantReturnPolicy"
AggregateOffer ||--}o TypeAndQuantityNode : "includesObject"
AggregateOffer ||--}o QuantitativeValue : "inventoryLevel"
AggregateOffer ||--}o OfferItemCondition : "itemCondition"
AggregateOffer ||--}o PriceSpecification : "priceSpecification"
AggregateOffer ||--}o Review : "review"
AggregateOffer ||--}o Review : "reviews"
AggregateOffer ||--}o OfferShippingDetails : "shippingDetails"
AggregateOffer ||--}o MemberProgramTier : "validForMemberTier"
AggregateOffer ||--}o WarrantyPromise : "warranty"
AggregateOffer ||--}o Action : "potentialAction"

