erDiagram
Airline {
    TextList iataCode  
    stringList actionableFeedbackPolicy  
    stringList areaServed  
    stringList correctionsPolicy  
    stringList diversityStaffingReport  
    TextList duns  
    stringList funder  
    TextList globalLocationNumber  
    URLList hasGS1DigitalLink  
    TextList leiCode  
    stringList location  
    stringList logo  
    stringList memberOf  
    stringList ownershipFundingInfo  
    stringList publishingPrinciples  
    stringList sponsor  
    TextList taxID  
    stringList unnamedSourcesPolicy  
    stringList acceptedPaymentMethod  
    stringList address  
    TextList award  
    TextList awards  
    stringList brand  
    DateList dissolutionDate  
    stringList diversityPolicy  
    TextList email  
    stringList ethicsPolicy  
    TextList faxNumber  
    stringList founder  
    DateList foundingDate  
    TextList isicV4  
    TextList iso6523Code  
    stringList keywords  
    stringList knowsAbout  
    stringList knowsLanguage  
    TextList legalName  
    stringList member  
    stringList members  
    TextList naics  
    stringList owns  
    stringList serviceArea  
    stringList skills  
    TextList slogan  
    TextList telephone  
    TextList vatID  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Airline ||--}o BoardingPolicyType : "boardingPolicy"
Airline ||--}o InteractionCounter : "agentInteractionStatistic"
Airline ||--}o AggregateRating : "aggregateRating"
Airline ||--}o Person : "alumni"
Airline ||--}o ContactPoint : "contactPoint"
Airline ||--}o ContactPoint : "contactPoints"
Airline ||--}o Organization : "department"
Airline ||--}o Person : "employee"
Airline ||--}o Person : "employees"
Airline ||--}o Event : "event"
Airline ||--}o Event : "events"
Airline ||--}o Person : "founders"
Airline ||--}o Place : "foundingLocation"
Airline ||--}o Grant : "funding"
Airline ||--}o Certification : "hasCertification"
Airline ||--}o EducationalOccupationalCredential : "hasCredential"
Airline ||--}o MemberProgram : "hasMemberProgram"
Airline ||--}o MerchantReturnPolicy : "hasMerchantReturnPolicy"
Airline ||--}o OfferCatalog : "hasOfferCatalog"
Airline ||--}o Place : "hasPOS"
Airline ||--}o InteractionCounter : "interactionStatistic"
Airline ||--}o Offer : "makesOffer"
Airline ||--}o NonprofitType : "nonprofitStatus"
Airline ||--}o QuantitativeValue : "numberOfEmployees"
Airline ||--}o Organization : "parentOrganization"
Airline ||--}o Review : "review"
Airline ||--}o Review : "reviews"
Airline ||--}o Demand : "seeks"
Airline ||--}o Organization : "subOrganization"
Airline ||--}o Action : "potentialAction"

