erDiagram
AlignmentObject {
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

AlignmentObject ||--}o Text : "alignmentType"
AlignmentObject ||--}o Text : "educationalFramework"
AlignmentObject ||--}o Text : "targetDescription"
AlignmentObject ||--}o Text : "targetName"
AlignmentObject ||--}o URL : "targetUrl"
AlignmentObject ||--}o Text : "alternateName"
AlignmentObject ||--}o Text : "disambiguatingDescription"
AlignmentObject ||--}o Text : "name"
AlignmentObject ||--}o URL : "sameAs"
AlignmentObject ||--}o Action : "potentialAction"
AlignmentObject ||--}o URL : "url"

