erDiagram
AnatomicalStructure {
    TextList associatedPathophysiology  
    TextList bodyLocation  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

AnatomicalStructure ||--}o AnatomicalStructure : "connectedTo"
AnatomicalStructure ||--}o ImageObject : "diagram"
AnatomicalStructure ||--}o AnatomicalSystem : "partOfSystem"
AnatomicalStructure ||--}o MedicalCondition : "relatedCondition"
AnatomicalStructure ||--}o MedicalTherapy : "relatedTherapy"
AnatomicalStructure ||--}o AnatomicalStructure : "subStructure"
AnatomicalStructure ||--}o MedicalCode : "code"
AnatomicalStructure ||--}o Grant : "funding"
AnatomicalStructure ||--}o MedicalGuideline : "guideline"
AnatomicalStructure ||--}o MedicineSystem : "medicineSystem"
AnatomicalStructure ||--}o Organization : "recognizingAuthority"
AnatomicalStructure ||--}o MedicalSpecialty : "relevantSpecialty"
AnatomicalStructure ||--}o MedicalStudy : "study"
AnatomicalStructure ||--}o Action : "potentialAction"

