erDiagram
BedDetails {
    NumberList numberOfBeds  
    stringList typeOfBed  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

BedDetails ||--}o Action : "potentialAction"

