erDiagram
BefriendAction {
    stringList location  
    stringList participant  
    stringList agent  
    stringList endTime  
    stringList provider  
    stringList startTime  
    stringList target  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

BefriendAction ||--}o Thing : "instrument"
BefriendAction ||--}o Thing : "object"
BefriendAction ||--}o Thing : "result"
BefriendAction ||--}o HowTo : "actionProcess"
BefriendAction ||--}o ActionStatusType : "actionStatus"
BefriendAction ||--}o Thing : "error"
BefriendAction ||--}o Text : "alternateName"
BefriendAction ||--}o Text : "disambiguatingDescription"
BefriendAction ||--}o Text : "name"
BefriendAction ||--}o URL : "sameAs"
BefriendAction ||--}o Action : "potentialAction"
BefriendAction ||--}o URL : "url"

