erDiagram
BrainStructure {
    TextList associatedPathophysiology  
    TextList bodyLocation  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

BrainStructure ||--}o AnatomicalStructure : "connectedTo"
BrainStructure ||--}o ImageObject : "diagram"
BrainStructure ||--}o AnatomicalSystem : "partOfSystem"
BrainStructure ||--}o MedicalCondition : "relatedCondition"
BrainStructure ||--}o MedicalTherapy : "relatedTherapy"
BrainStructure ||--}o AnatomicalStructure : "subStructure"
BrainStructure ||--}o MedicalCode : "code"
BrainStructure ||--}o Grant : "funding"
BrainStructure ||--}o MedicalGuideline : "guideline"
BrainStructure ||--}o MedicineSystem : "medicineSystem"
BrainStructure ||--}o Organization : "recognizingAuthority"
BrainStructure ||--}o MedicalSpecialty : "relevantSpecialty"
BrainStructure ||--}o MedicalStudy : "study"
BrainStructure ||--}o Action : "potentialAction"

