erDiagram
Brand {
    stringList logo  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

Brand ||--}o AggregateRating : "aggregateRating"
Brand ||--}o Review : "review"
Brand ||--}o Text : "slogan"
Brand ||--}o Text : "alternateName"
Brand ||--}o Text : "disambiguatingDescription"
Brand ||--}o Text : "name"
Brand ||--}o URL : "sameAs"
Brand ||--}o Action : "potentialAction"
Brand ||--}o URL : "url"

