erDiagram
Brand {
    stringList logo  
    TextList slogan  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Brand ||--}o AggregateRating : "aggregateRating"
Brand ||--}o Review : "review"
Brand ||--}o Action : "potentialAction"

