erDiagram
BroadcastChannel {
    stringList genre  
    TextList broadcastChannelId  
    stringList broadcastFrequency  
    TextList broadcastServiceTier  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

BroadcastChannel ||--}o CableOrSatelliteService : "inBroadcastLineup"
BroadcastChannel ||--}o BroadcastService : "providesBroadcastService"
BroadcastChannel ||--}o Action : "potentialAction"

