erDiagram
BusOrCoach {
    stringList bodyType  
    stringList driveWheelConfiguration  
    stringList fuelType  
    stringList meetsEmissionStandard  
    stringList numberOfAirbags  
    stringList numberOfAxles  
    stringList numberOfDoors  
    stringList numberOfForwardGears  
    stringList numberOfPreviousOwners  
    stringList seatingCapacity  
    stringList vehicleSeatingCapacity  
    stringList vehicleSpecialUsage  
    stringList vehicleTransmission  
    stringList asin  
    stringList category  
    stringList colorSwatch  
    stringList gtin  
    stringList logo  
    stringList material  
    stringList brand  
    stringList depth  
    stringList height  
    stringList isRelatedTo  
    stringList isSimilarTo  
    stringList isVariantOf  
    stringList keywords  
    stringList model  
    stringList negativeNotes  
    stringList offers  
    stringList pattern  
    stringList positiveNotes  
    stringList size  
    stringList width  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

BusOrCoach ||--}o Text : "acrissCode"
BusOrCoach ||--}o QuantitativeValue : "roofLoad"
BusOrCoach ||--}o Text : "callSign"
BusOrCoach ||--}o Text : "vehicleIdentificationNumber"
BusOrCoach ||--}o QuantitativeValue : "accelerationTime"
BusOrCoach ||--}o QuantitativeValue : "cargoVolume"
BusOrCoach ||--}o Date : "dateVehicleFirstRegistered"
BusOrCoach ||--}o Number : "emissionsCO2"
BusOrCoach ||--}o QuantitativeValue : "fuelCapacity"
BusOrCoach ||--}o QuantitativeValue : "fuelConsumption"
BusOrCoach ||--}o QuantitativeValue : "fuelEfficiency"
BusOrCoach ||--}o Text : "knownVehicleDamages"
BusOrCoach ||--}o QuantitativeValue : "mileageFromOdometer"
BusOrCoach ||--}o Date : "modelDate"
BusOrCoach ||--}o QuantitativeValue : "payload"
BusOrCoach ||--}o Date : "productionDate"
BusOrCoach ||--}o Date : "purchaseDate"
BusOrCoach ||--}o QuantitativeValue : "speed"
BusOrCoach ||--}o SteeringPositionValue : "steeringPosition"
BusOrCoach ||--}o QuantitativeValue : "tongueWeight"
BusOrCoach ||--}o QuantitativeValue : "trailerWeight"
BusOrCoach ||--}o Text : "vehicleConfiguration"
BusOrCoach ||--}o EngineSpecification : "vehicleEngine"
BusOrCoach ||--}o Text : "vehicleInteriorColor"
BusOrCoach ||--}o Text : "vehicleInteriorType"
BusOrCoach ||--}o Date : "vehicleModelDate"
BusOrCoach ||--}o QuantitativeValue : "weightTotal"
BusOrCoach ||--}o QuantitativeValue : "wheelbase"
BusOrCoach ||--}o Text : "gtin12"
BusOrCoach ||--}o Text : "gtin13"
BusOrCoach ||--}o Text : "gtin14"
BusOrCoach ||--}o Text : "gtin8"
BusOrCoach ||--}o URL : "hasGS1DigitalLink"
BusOrCoach ||--}o Text : "nsn"
BusOrCoach ||--}o Text : "productID"
BusOrCoach ||--}o Text : "sku"
BusOrCoach ||--}o PropertyValue : "additionalProperty"
BusOrCoach ||--}o AggregateRating : "aggregateRating"
BusOrCoach ||--}o Audience : "audience"
BusOrCoach ||--}o Text : "award"
BusOrCoach ||--}o Text : "awards"
BusOrCoach ||--}o Text : "color"
BusOrCoach ||--}o Text : "countryOfAssembly"
BusOrCoach ||--}o Text : "countryOfLastProcessing"
BusOrCoach ||--}o Country : "countryOfOrigin"
BusOrCoach ||--}o Grant : "funding"
BusOrCoach ||--}o AdultOrientedEnumeration : "hasAdultConsideration"
BusOrCoach ||--}o Certification : "hasCertification"
BusOrCoach ||--}o EnergyConsumptionDetails : "hasEnergyConsumptionDetails"
BusOrCoach ||--}o QuantitativeValue : "hasMeasurement"
BusOrCoach ||--}o MerchantReturnPolicy : "hasMerchantReturnPolicy"
BusOrCoach ||--}o Text : "inProductGroupWithID"
BusOrCoach ||--}o Product : "isAccessoryOrSparePartFor"
BusOrCoach ||--}o Product : "isConsumableFor"
BusOrCoach ||--}o Boolean : "isFamilyFriendly"
BusOrCoach ||--}o OfferItemCondition : "itemCondition"
BusOrCoach ||--}o Organization : "manufacturer"
BusOrCoach ||--}o Text : "mobileUrl"
BusOrCoach ||--}o Text : "mpn"
BusOrCoach ||--}o Date : "releaseDate"
BusOrCoach ||--}o Review : "review"
BusOrCoach ||--}o Review : "reviews"
BusOrCoach ||--}o Text : "slogan"
BusOrCoach ||--}o QuantitativeValue : "weight"
BusOrCoach ||--}o Text : "alternateName"
BusOrCoach ||--}o Text : "disambiguatingDescription"
BusOrCoach ||--}o Text : "name"
BusOrCoach ||--}o URL : "sameAs"
BusOrCoach ||--}o Action : "potentialAction"
BusOrCoach ||--}o URL : "url"

