erDiagram
BusTrip {
    stringList arrivalBusStop  
    TextList busName  
    TextList busNumber  
    stringList departureBusStop  
    stringList arrivalTime  
    stringList departureTime  
    stringList itinerary  
    stringList offers  
    stringList provider  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

BusTrip ||--}o Trip : "partOfTrip"
BusTrip ||--}o Trip : "subTrip"
BusTrip ||--}o Place : "tripOrigin"
BusTrip ||--}o Action : "potentialAction"

