erDiagram
Car {
    TextList acrissCode  
    TextList callSign  
    TextList vehicleIdentificationNumber  
    stringList bodyType  
    DateList dateVehicleFirstRegistered  
    stringList driveWheelConfiguration  
    NumberList emissionsCO2  
    stringList fuelType  
    TextList knownVehicleDamages  
    stringList meetsEmissionStandard  
    DateList modelDate  
    stringList numberOfAirbags  
    stringList numberOfAxles  
    stringList numberOfDoors  
    stringList numberOfForwardGears  
    stringList numberOfPreviousOwners  
    DateList productionDate  
    DateList purchaseDate  
    stringList seatingCapacity  
    TextList vehicleConfiguration  
    TextList vehicleInteriorColor  
    TextList vehicleInteriorType  
    DateList vehicleModelDate  
    stringList vehicleSeatingCapacity  
    stringList vehicleSpecialUsage  
    stringList vehicleTransmission  
    stringList asin  
    stringList category  
    stringList colorSwatch  
    stringList gtin  
    TextList gtin12  
    TextList gtin13  
    TextList gtin14  
    TextList gtin8  
    URLList hasGS1DigitalLink  
    stringList logo  
    stringList material  
    TextList nsn  
    TextList productID  
    TextList sku  
    TextList award  
    TextList awards  
    stringList brand  
    TextList color  
    TextList countryOfAssembly  
    TextList countryOfLastProcessing  
    stringList depth  
    stringList height  
    TextList inProductGroupWithID  
    BooleanList isFamilyFriendly  
    stringList isRelatedTo  
    stringList isSimilarTo  
    stringList isVariantOf  
    stringList keywords  
    TextList mobileUrl  
    stringList model  
    TextList mpn  
    stringList negativeNotes  
    stringList offers  
    stringList pattern  
    stringList positiveNotes  
    DateList releaseDate  
    stringList size  
    TextList slogan  
    stringList width  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Car ||--}o QuantitativeValue : "roofLoad"
Car ||--}o QuantitativeValue : "accelerationTime"
Car ||--}o QuantitativeValue : "cargoVolume"
Car ||--}o QuantitativeValue : "fuelCapacity"
Car ||--}o QuantitativeValue : "fuelConsumption"
Car ||--}o QuantitativeValue : "fuelEfficiency"
Car ||--}o QuantitativeValue : "mileageFromOdometer"
Car ||--}o QuantitativeValue : "payload"
Car ||--}o QuantitativeValue : "speed"
Car ||--}o SteeringPositionValue : "steeringPosition"
Car ||--}o QuantitativeValue : "tongueWeight"
Car ||--}o QuantitativeValue : "trailerWeight"
Car ||--}o EngineSpecification : "vehicleEngine"
Car ||--}o QuantitativeValue : "weightTotal"
Car ||--}o QuantitativeValue : "wheelbase"
Car ||--}o PropertyValue : "additionalProperty"
Car ||--}o AggregateRating : "aggregateRating"
Car ||--}o Audience : "audience"
Car ||--}o Country : "countryOfOrigin"
Car ||--}o Grant : "funding"
Car ||--}o AdultOrientedEnumeration : "hasAdultConsideration"
Car ||--}o Certification : "hasCertification"
Car ||--}o EnergyConsumptionDetails : "hasEnergyConsumptionDetails"
Car ||--}o QuantitativeValue : "hasMeasurement"
Car ||--}o MerchantReturnPolicy : "hasMerchantReturnPolicy"
Car ||--}o Product : "isAccessoryOrSparePartFor"
Car ||--}o Product : "isConsumableFor"
Car ||--}o OfferItemCondition : "itemCondition"
Car ||--}o Organization : "manufacturer"
Car ||--}o Review : "review"
Car ||--}o Review : "reviews"
Car ||--}o QuantitativeValue : "weight"
Car ||--}o Action : "potentialAction"

