erDiagram
CategoryCode {
    TextList codeValue  
    stringList inCodeSet  
    stringList inDefinedTermSet  
    TextList termCode  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

CategoryCode ||--}o Action : "potentialAction"

