erDiagram
CDCPMDRecord {
    stringList cvdCollectionDate  
    TextList cvdFacilityCounty  
    TextList cvdFacilityId  
    NumberList cvdNumBeds  
    NumberList cvdNumBedsOcc  
    NumberList cvdNumC19Died  
    NumberList cvdNumC19HOPats  
    NumberList cvdNumC19HospPats  
    NumberList cvdNumC19MechVentPats  
    NumberList cvdNumC19OFMechVentPats  
    NumberList cvdNumC19OverflowPats  
    NumberList cvdNumICUBeds  
    NumberList cvdNumICUBedsOcc  
    NumberList cvdNumTotBeds  
    NumberList cvdNumVent  
    NumberList cvdNumVentUse  
    stringList datePosted  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

CDCPMDRecord ||--}o Action : "potentialAction"

