erDiagram
ChildrensEvent {
    stringList actor  
    stringList contributor  
    stringList funder  
    stringList location  
    stringList sponsor  
    stringList attendee  
    stringList attendees  
    stringList composer  
    stringList doorTime  
    stringList endDate  
    stringList inLanguage  
    BooleanList isAccessibleForFree  
    stringList keywords  
    IntegerList maximumAttendeeCapacity  
    IntegerList maximumPhysicalAttendeeCapacity  
    IntegerList maximumVirtualAttendeeCapacity  
    stringList offers  
    stringList organizer  
    stringList performer  
    stringList performers  
    DateList previousStartDate  
    IntegerList remainingAttendeeCapacity  
    stringList startDate  
    stringList translator  
    TextList typicalAgeRange  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

ChildrensEvent ||--}o Thing : "about"
ChildrensEvent ||--}o Duration : "duration"
ChildrensEvent ||--}o CreativeWork : "workFeatured"
ChildrensEvent ||--}o CreativeWork : "workPerformed"
ChildrensEvent ||--}o AggregateRating : "aggregateRating"
ChildrensEvent ||--}o Audience : "audience"
ChildrensEvent ||--}o Person : "director"
ChildrensEvent ||--}o EventAttendanceModeEnumeration : "eventAttendanceMode"
ChildrensEvent ||--}o Schedule : "eventSchedule"
ChildrensEvent ||--}o EventStatusType : "eventStatus"
ChildrensEvent ||--}o Grant : "funding"
ChildrensEvent ||--}o CreativeWork : "recordedIn"
ChildrensEvent ||--}o Review : "review"
ChildrensEvent ||--}o Event : "subEvent"
ChildrensEvent ||--}o Event : "subEvents"
ChildrensEvent ||--}o Event : "superEvent"
ChildrensEvent ||--}o Action : "potentialAction"

