erDiagram
Class {
    stringList supersededBy  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

Class ||--}o Text : "alternateName"
Class ||--}o Text : "disambiguatingDescription"
Class ||--}o Text : "name"
Class ||--}o URL : "sameAs"
Class ||--}o Action : "potentialAction"
Class ||--}o URL : "url"

