erDiagram
ComicCoverArt {
    stringList artMedium  
    stringList surface  
    stringList artEdition  
    stringList artform  
    stringList artworkSurface  
    stringList depth  
    stringList height  
    stringList width  
    stringList acquireLicensePage  
    stringList contributor  
    stringList creator  
    stringList dateCreated  
    stringList editEIDR  
    stringList funder  
    stringList genre  
    stringList isPartOf  
    stringList material  
    stringList position  
    stringList publishingPrinciples  
    stringList sponsor  
    stringList usageInfo  
    TextList abstract  
    TextList accessMode  
    TextList accessibilityAPI  
    TextList accessibilityControl  
    TextList accessibilityFeature  
    TextList accessibilityHazard  
    TextList accessibilitySummary  
    TextList alternativeHeadline  
    stringList archivedAt  
    stringList assesses  
    stringList audio  
    stringList author  
    TextList award  
    TextList awards  
    stringList citation  
    IntegerList commentCount  
    TextList conditionsOfAccess  
    stringList contentRating  
    DateTimeList contentReferenceTime  
    stringList copyrightHolder  
    TextList copyrightNotice  
    NumberList copyrightYear  
    stringList correction  
    stringList creativeWorkStatus  
    TextList creditText  
    stringList dateModified  
    stringList datePublished  
    URLList discussionUrl  
    stringList educationalLevel  
    stringList educationalUse  
    stringList encodingFormat  
    stringList expires  
    stringList fileFormat  
    TextList headline  
    stringList inLanguage  
    TextList interactivityType  
    BooleanList isAccessibleForFree  
    stringList isBasedOn  
    stringList isBasedOnUrl  
    BooleanList isFamilyFriendly  
    stringList keywords  
    stringList learningResourceType  
    stringList license  
    stringList maintainer  
    stringList materialExtent  
    stringList offers  
    stringList pattern  
    stringList producer  
    stringList provider  
    stringList publisher  
    stringList schemaVersion  
    DateList sdDatePublished  
    stringList sdLicense  
    stringList sdPublisher  
    stringList size  
    stringList teaches  
    stringList temporal  
    stringList temporalCoverage  
    TextList text  
    URLList thumbnailUrl  
    stringList translator  
    TextList typicalAgeRange  
    stringList version  
    stringList video  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

ComicCoverArt ||--}o Person : "artist"
ComicCoverArt ||--}o Person : "colorist"
ComicCoverArt ||--}o Person : "inker"
ComicCoverArt ||--}o Person : "letterer"
ComicCoverArt ||--}o Person : "penciler"
ComicCoverArt ||--}o QuantitativeValue : "weight"
ComicCoverArt ||--}o Thing : "about"
ComicCoverArt ||--}o Place : "contentLocation"
ComicCoverArt ||--}o CreativeWork : "hasPart"
ComicCoverArt ||--}o Claim : "interpretedAsClaim"
ComicCoverArt ||--}o Thing : "mainEntity"
ComicCoverArt ||--}o Place : "spatialCoverage"
ComicCoverArt ||--}o CreativeWork : "workExample"
ComicCoverArt ||--}o ItemList : "accessModeSufficient"
ComicCoverArt ||--}o Person : "accountablePerson"
ComicCoverArt ||--}o AggregateRating : "aggregateRating"
ComicCoverArt ||--}o MediaObject : "associatedMedia"
ComicCoverArt ||--}o Audience : "audience"
ComicCoverArt ||--}o Person : "character"
ComicCoverArt ||--}o Comment : "comment"
ComicCoverArt ||--}o Country : "countryOfOrigin"
ComicCoverArt ||--}o IPTCDigitalSourceEnumeration : "digitalSourceType"
ComicCoverArt ||--}o Person : "editor"
ComicCoverArt ||--}o AlignmentObject : "educationalAlignment"
ComicCoverArt ||--}o MediaObject : "encoding"
ComicCoverArt ||--}o MediaObject : "encodings"
ComicCoverArt ||--}o CreativeWork : "exampleOfWork"
ComicCoverArt ||--}o Grant : "funding"
ComicCoverArt ||--}o InteractionCounter : "interactionStatistic"
ComicCoverArt ||--}o Place : "locationCreated"
ComicCoverArt ||--}o Thing : "mentions"
ComicCoverArt ||--}o PublicationEvent : "publication"
ComicCoverArt ||--}o Organization : "publisherImprint"
ComicCoverArt ||--}o Event : "recordedAt"
ComicCoverArt ||--}o PublicationEvent : "releasedEvent"
ComicCoverArt ||--}o Review : "review"
ComicCoverArt ||--}o Review : "reviews"
ComicCoverArt ||--}o Organization : "sourceOrganization"
ComicCoverArt ||--}o Place : "spatial"
ComicCoverArt ||--}o ImageObject : "thumbnail"
ComicCoverArt ||--}o Duration : "timeRequired"
ComicCoverArt ||--}o CreativeWork : "translationOfWork"
ComicCoverArt ||--}o CreativeWork : "workTranslation"
ComicCoverArt ||--}o Action : "potentialAction"

