erDiagram
ComputerLanguage {
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

ComputerLanguage ||--}o Text : "alternateName"
ComputerLanguage ||--}o Text : "disambiguatingDescription"
ComputerLanguage ||--}o Text : "name"
ComputerLanguage ||--}o URL : "sameAs"
ComputerLanguage ||--}o Action : "potentialAction"
ComputerLanguage ||--}o URL : "url"

