erDiagram
ConstraintNode {
    stringList constraintProperty  
    IntegerList numConstraints  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

ConstraintNode ||--}o Action : "potentialAction"

