erDiagram
ContactPoint {
    stringList areaServed  
    stringList availableLanguage  
    TextList contactType  
    TextList email  
    TextList faxNumber  
    stringList productSupported  
    stringList serviceArea  
    TextList telephone  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

ContactPoint ||--}o ContactPointOption : "contactOption"
ContactPoint ||--}o OpeningHoursSpecification : "hoursAvailable"
ContactPoint ||--}o Action : "potentialAction"

