erDiagram
CreateAction {
    stringList location  
    stringList participant  
    stringList agent  
    stringList endTime  
    stringList provider  
    stringList startTime  
    stringList target  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

CreateAction ||--}o Thing : "instrument"
CreateAction ||--}o Thing : "object"
CreateAction ||--}o Thing : "result"
CreateAction ||--}o HowTo : "actionProcess"
CreateAction ||--}o ActionStatusType : "actionStatus"
CreateAction ||--}o Thing : "error"
CreateAction ||--}o Text : "alternateName"
CreateAction ||--}o Text : "disambiguatingDescription"
CreateAction ||--}o Text : "name"
CreateAction ||--}o URL : "sameAs"
CreateAction ||--}o Action : "potentialAction"
CreateAction ||--}o URL : "url"

