erDiagram
DatedMoneySpecification {
    stringList amount  
    TextList currency  
    stringList endDate  
    stringList startDate  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

DatedMoneySpecification ||--}o Action : "potentialAction"

