erDiagram
DefinedRegion {
    stringList addressCountry  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

DefinedRegion ||--}o Text : "addressRegion"
DefinedRegion ||--}o Text : "postalCode"
DefinedRegion ||--}o Text : "postalCodePrefix"
DefinedRegion ||--}o PostalCodeRangeSpecification : "postalCodeRange"
DefinedRegion ||--}o Text : "alternateName"
DefinedRegion ||--}o Text : "disambiguatingDescription"
DefinedRegion ||--}o Text : "name"
DefinedRegion ||--}o URL : "sameAs"
DefinedRegion ||--}o Action : "potentialAction"
DefinedRegion ||--}o URL : "url"

