erDiagram
DefinedRegion {
    stringList addressCountry  
    TextList addressRegion  
    TextList postalCode  
    TextList postalCodePrefix  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

DefinedRegion ||--}o PostalCodeRangeSpecification : "postalCodeRange"
DefinedRegion ||--}o Action : "potentialAction"

