erDiagram
DeleteAction {
    stringList location  
    stringList participant  
    stringList agent  
    stringList endTime  
    stringList provider  
    stringList startTime  
    stringList target  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

DeleteAction ||--}o Thing : "collection"
DeleteAction ||--}o Thing : "targetCollection"
DeleteAction ||--}o Thing : "instrument"
DeleteAction ||--}o Thing : "object"
DeleteAction ||--}o Thing : "result"
DeleteAction ||--}o HowTo : "actionProcess"
DeleteAction ||--}o ActionStatusType : "actionStatus"
DeleteAction ||--}o Thing : "error"
DeleteAction ||--}o Text : "alternateName"
DeleteAction ||--}o Text : "disambiguatingDescription"
DeleteAction ||--}o Text : "name"
DeleteAction ||--}o URL : "sameAs"
DeleteAction ||--}o Action : "potentialAction"
DeleteAction ||--}o URL : "url"

