erDiagram
DeliveryTimeSettings {
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

DeliveryTimeSettings ||--}o ShippingDeliveryTime : "deliveryTime"
DeliveryTimeSettings ||--}o Boolean : "isUnlabelledFallback"
DeliveryTimeSettings ||--}o DefinedRegion : "shippingDestination"
DeliveryTimeSettings ||--}o Text : "transitTimeLabel"
DeliveryTimeSettings ||--}o Text : "alternateName"
DeliveryTimeSettings ||--}o Text : "disambiguatingDescription"
DeliveryTimeSettings ||--}o Text : "name"
DeliveryTimeSettings ||--}o URL : "sameAs"
DeliveryTimeSettings ||--}o Action : "potentialAction"
DeliveryTimeSettings ||--}o URL : "url"

