erDiagram
DeliveryChargeSpecification {
    stringList areaServed  
    stringList eligibleRegion  
    stringList ineligibleRegion  
    NumberList maxPrice  
    stringList membershipPointsEarned  
    NumberList minPrice  
    stringList price  
    TextList priceCurrency  
    stringList validFrom  
    stringList validThrough  
    BooleanList valueAddedTaxIncluded  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

DeliveryChargeSpecification ||--}o DeliveryMethod : "appliesToDeliveryMethod"
DeliveryChargeSpecification ||--}o QuantitativeValue : "eligibleQuantity"
DeliveryChargeSpecification ||--}o PriceSpecification : "eligibleTransactionVolume"
DeliveryChargeSpecification ||--}o MemberProgramTier : "validForMemberTier"
DeliveryChargeSpecification ||--}o Action : "potentialAction"

