erDiagram
Demand {
    stringList areaServed  
    stringList asin  
    stringList eligibleRegion  
    stringList gtin  
    TextList gtin12  
    TextList gtin13  
    TextList gtin14  
    TextList gtin8  
    stringList seller  
    TextList serialNumber  
    TextList sku  
    stringList acceptedPaymentMethod  
    stringList availabilityEnds  
    stringList availabilityStarts  
    stringList ineligibleRegion  
    stringList itemOffered  
    TextList mpn  
    stringList validFrom  
    stringList validThrough  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Demand ||--}o Place : "availableAtOrFrom"
Demand ||--}o QuantitativeValue : "advanceBookingRequirement"
Demand ||--}o ItemAvailability : "availability"
Demand ||--}o DeliveryMethod : "availableDeliveryMethod"
Demand ||--}o BusinessFunction : "businessFunction"
Demand ||--}o QuantitativeValue : "deliveryLeadTime"
Demand ||--}o BusinessEntityType : "eligibleCustomerType"
Demand ||--}o QuantitativeValue : "eligibleDuration"
Demand ||--}o QuantitativeValue : "eligibleQuantity"
Demand ||--}o PriceSpecification : "eligibleTransactionVolume"
Demand ||--}o TypeAndQuantityNode : "includesObject"
Demand ||--}o QuantitativeValue : "inventoryLevel"
Demand ||--}o OfferItemCondition : "itemCondition"
Demand ||--}o PriceSpecification : "priceSpecification"
Demand ||--}o WarrantyPromise : "warranty"
Demand ||--}o Action : "potentialAction"

