erDiagram
DietarySupplement {
    TextList activeIngredient  
    BooleanList isProprietary  
    stringList legalStatus  
    TextList mechanismOfAction  
    TextList nonProprietaryName  
    TextList proprietaryName  
    TextList safetyConsideration  
    TextList targetPopulation  
    stringList asin  
    stringList category  
    stringList colorSwatch  
    stringList gtin  
    TextList gtin12  
    TextList gtin13  
    TextList gtin14  
    TextList gtin8  
    URLList hasGS1DigitalLink  
    stringList logo  
    stringList material  
    TextList nsn  
    TextList productID  
    TextList sku  
    TextList award  
    TextList awards  
    stringList brand  
    TextList color  
    TextList countryOfAssembly  
    TextList countryOfLastProcessing  
    stringList depth  
    stringList height  
    TextList inProductGroupWithID  
    BooleanList isFamilyFriendly  
    stringList isRelatedTo  
    stringList isSimilarTo  
    stringList isVariantOf  
    stringList keywords  
    TextList mobileUrl  
    stringList model  
    TextList mpn  
    stringList negativeNotes  
    stringList offers  
    stringList pattern  
    stringList positiveNotes  
    DateList productionDate  
    DateList purchaseDate  
    DateList releaseDate  
    stringList size  
    TextList slogan  
    stringList width  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

DietarySupplement ||--}o MaximumDoseSchedule : "maximumIntake"
DietarySupplement ||--}o RecommendedDoseSchedule : "recommendedIntake"
DietarySupplement ||--}o PropertyValue : "additionalProperty"
DietarySupplement ||--}o AggregateRating : "aggregateRating"
DietarySupplement ||--}o Audience : "audience"
DietarySupplement ||--}o Country : "countryOfOrigin"
DietarySupplement ||--}o Grant : "funding"
DietarySupplement ||--}o AdultOrientedEnumeration : "hasAdultConsideration"
DietarySupplement ||--}o Certification : "hasCertification"
DietarySupplement ||--}o EnergyConsumptionDetails : "hasEnergyConsumptionDetails"
DietarySupplement ||--}o QuantitativeValue : "hasMeasurement"
DietarySupplement ||--}o MerchantReturnPolicy : "hasMerchantReturnPolicy"
DietarySupplement ||--}o Product : "isAccessoryOrSparePartFor"
DietarySupplement ||--}o Product : "isConsumableFor"
DietarySupplement ||--}o OfferItemCondition : "itemCondition"
DietarySupplement ||--}o Organization : "manufacturer"
DietarySupplement ||--}o Review : "review"
DietarySupplement ||--}o Review : "reviews"
DietarySupplement ||--}o QuantitativeValue : "weight"
DietarySupplement ||--}o Action : "potentialAction"
DietarySupplement ||--}o MedicalCode : "code"
DietarySupplement ||--}o MedicalGuideline : "guideline"
DietarySupplement ||--}o MedicineSystem : "medicineSystem"
DietarySupplement ||--}o Organization : "recognizingAuthority"
DietarySupplement ||--}o MedicalSpecialty : "relevantSpecialty"
DietarySupplement ||--}o MedicalStudy : "study"

