erDiagram
DigitalPlatformEnumeration {
    stringList supersededBy  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

DigitalPlatformEnumeration ||--}o Text : "alternateName"
DigitalPlatformEnumeration ||--}o Text : "disambiguatingDescription"
DigitalPlatformEnumeration ||--}o Text : "name"
DigitalPlatformEnumeration ||--}o URL : "sameAs"
DigitalPlatformEnumeration ||--}o Action : "potentialAction"
DigitalPlatformEnumeration ||--}o URL : "url"

