erDiagram
DriveWheelConfigurationValue {
    stringList valueReference  
    stringList supersededBy  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

DriveWheelConfigurationValue ||--}o PropertyValue : "additionalProperty"
DriveWheelConfigurationValue ||--}o QualitativeValue : "equal"
DriveWheelConfigurationValue ||--}o QualitativeValue : "greater"
DriveWheelConfigurationValue ||--}o QualitativeValue : "greaterOrEqual"
DriveWheelConfigurationValue ||--}o QualitativeValue : "lesser"
DriveWheelConfigurationValue ||--}o QualitativeValue : "lesserOrEqual"
DriveWheelConfigurationValue ||--}o QualitativeValue : "nonEqual"
DriveWheelConfigurationValue ||--}o Action : "potentialAction"

