erDiagram
DrugClass {
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

DrugClass ||--}o Drug : "drug"
DrugClass ||--}o MedicalCode : "code"
DrugClass ||--}o Grant : "funding"
DrugClass ||--}o MedicalGuideline : "guideline"
DrugClass ||--}o MedicineSystem : "medicineSystem"
DrugClass ||--}o Organization : "recognizingAuthority"
DrugClass ||--}o MedicalSpecialty : "relevantSpecialty"
DrugClass ||--}o MedicalStudy : "study"
DrugClass ||--}o Action : "potentialAction"

