erDiagram
EducationalOccupationalProgram {
    stringList applicationDeadline  
    DateList applicationStartDate  
    stringList educationalCredentialAwarded  
    stringList educationalProgramMode  
    stringList endDate  
    stringList financialAidEligible  
    IntegerList maximumEnrollment  
    stringList numberOfCredits  
    stringList occupationalCategory  
    stringList occupationalCredentialAwarded  
    stringList offers  
    stringList programPrerequisites  
    stringList programType  
    stringList provider  
    stringList startDate  
    NumberList termsPerYear  
    TextList timeOfDay  
    stringList typicalCreditsPerTerm  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

EducationalOccupationalProgram ||--}o DayOfWeek : "dayOfWeek"
EducationalOccupationalProgram ||--}o Course : "hasCourse"
EducationalOccupationalProgram ||--}o MonetaryAmountDistribution : "salaryUponCompletion"
EducationalOccupationalProgram ||--}o Duration : "termDuration"
EducationalOccupationalProgram ||--}o Duration : "timeToComplete"
EducationalOccupationalProgram ||--}o MonetaryAmountDistribution : "trainingSalary"
EducationalOccupationalProgram ||--}o Action : "potentialAction"

