erDiagram
EducationalAudience {
    TextList educationalRole  
    TextList audienceType  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

EducationalAudience ||--}o AdministrativeArea : "geographicArea"
EducationalAudience ||--}o Action : "potentialAction"

