erDiagram
EmployeeRole {
    stringList baseSalary  
    TextList salaryCurrency  
    NumberList numberedPosition  
    stringList endDate  
    stringList namedPosition  
    stringList roleName  
    stringList startDate  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

EmployeeRole ||--}o Action : "potentialAction"

