erDiagram
EndorsementRating {
    stringList author  
    stringList bestRating  
    TextList ratingExplanation  
    stringList ratingValue  
    TextList reviewAspect  
    stringList worstRating  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

EndorsementRating ||--}o Action : "potentialAction"

