erDiagram
Energy {
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

Energy ||--}o Text : "alternateName"
Energy ||--}o Text : "disambiguatingDescription"
Energy ||--}o Text : "name"
Energy ||--}o URL : "sameAs"
Energy ||--}o Action : "potentialAction"
Energy ||--}o URL : "url"

