erDiagram
EnergyStarEnergyEfficiencyEnumeration {
    stringList supersededBy  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

EnergyStarEnergyEfficiencyEnumeration ||--}o Text : "alternateName"
EnergyStarEnergyEfficiencyEnumeration ||--}o Text : "disambiguatingDescription"
EnergyStarEnergyEfficiencyEnumeration ||--}o Text : "name"
EnergyStarEnergyEfficiencyEnumeration ||--}o URL : "sameAs"
EnergyStarEnergyEfficiencyEnumeration ||--}o Action : "potentialAction"
EnergyStarEnergyEfficiencyEnumeration ||--}o URL : "url"

