erDiagram
EntryPoint {
    stringList actionPlatform  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

EntryPoint ||--}o SoftwareApplication : "actionApplication"
EntryPoint ||--}o SoftwareApplication : "application"
EntryPoint ||--}o Text : "contentType"
EntryPoint ||--}o Text : "encodingType"
EntryPoint ||--}o Text : "httpMethod"
EntryPoint ||--}o Text : "urlTemplate"
EntryPoint ||--}o Text : "alternateName"
EntryPoint ||--}o Text : "disambiguatingDescription"
EntryPoint ||--}o Text : "name"
EntryPoint ||--}o URL : "sameAs"
EntryPoint ||--}o Action : "potentialAction"
EntryPoint ||--}o URL : "url"

