erDiagram
Enumeration {
    stringList supersededBy  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

Enumeration ||--}o Text : "alternateName"
Enumeration ||--}o Text : "disambiguatingDescription"
Enumeration ||--}o Text : "name"
Enumeration ||--}o URL : "sameAs"
Enumeration ||--}o Action : "potentialAction"
Enumeration ||--}o URL : "url"

