erDiagram
ExchangeRateSpecification {
    TextList currency  
    stringList exchangeRateSpread  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

ExchangeRateSpecification ||--}o UnitPriceSpecification : "currentExchangeRate"
ExchangeRateSpecification ||--}o Action : "potentialAction"

