erDiagram
FlightReservation {
    stringList passengerPriorityStatus  
    stringList bookingAgent  
    stringList broker  
    stringList provider  
    stringList totalPrice  
    stringList underName  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

FlightReservation ||--}o Text : "boardingGroup"
FlightReservation ||--}o Text : "passengerSequenceNumber"
FlightReservation ||--}o Text : "securityScreening"
FlightReservation ||--}o DateTime : "bookingTime"
FlightReservation ||--}o DateTime : "modifiedTime"
FlightReservation ||--}o Text : "priceCurrency"
FlightReservation ||--}o ProgramMembership : "programMembershipUsed"
FlightReservation ||--}o Thing : "reservationFor"
FlightReservation ||--}o Text : "reservationId"
FlightReservation ||--}o ReservationStatusType : "reservationStatus"
FlightReservation ||--}o Ticket : "reservedTicket"
FlightReservation ||--}o Text : "alternateName"
FlightReservation ||--}o Text : "disambiguatingDescription"
FlightReservation ||--}o Text : "name"
FlightReservation ||--}o URL : "sameAs"
FlightReservation ||--}o Action : "potentialAction"
FlightReservation ||--}o URL : "url"

