erDiagram
Flight {
    TextList flightNumber  
    stringList seller  
    stringList aircraft  
    TextList arrivalGate  
    TextList arrivalTerminal  
    TextList departureGate  
    TextList departureTerminal  
    stringList estimatedFlightDuration  
    stringList flightDistance  
    TextList mealService  
    DateTimeList webCheckinTime  
    stringList arrivalTime  
    stringList departureTime  
    stringList itinerary  
    stringList offers  
    stringList provider  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Flight ||--}o Airport : "arrivalAirport"
Flight ||--}o BoardingPolicyType : "boardingPolicy"
Flight ||--}o Organization : "carrier"
Flight ||--}o Airport : "departureAirport"
Flight ||--}o Trip : "partOfTrip"
Flight ||--}o Trip : "subTrip"
Flight ||--}o Place : "tripOrigin"
Flight ||--}o Action : "potentialAction"

