erDiagram
GameServer {
    IntegerList playersOnline  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

GameServer ||--}o VideoGame : "game"
GameServer ||--}o GameServerStatus : "serverStatus"
GameServer ||--}o Action : "potentialAction"

