erDiagram
GeoShape {
    stringList address  
    stringList addressCountry  
    TextList box  
    TextList circle  
    stringList elevation  
    TextList line  
    TextList polygon  
    TextList postalCode  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

GeoShape ||--}o Action : "potentialAction"

