erDiagram
GovernmentPermit {
    stringList validFrom  
    DateList validUntil  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

GovernmentPermit ||--}o Organization : "issuedBy"
GovernmentPermit ||--}o Service : "issuedThrough"
GovernmentPermit ||--}o Audience : "permitAudience"
GovernmentPermit ||--}o Duration : "validFor"
GovernmentPermit ||--}o AdministrativeArea : "validIn"
GovernmentPermit ||--}o Action : "potentialAction"

