erDiagram
HealthInsurancePlan {
    URLList benefitsSummaryUrl  
    TextList healthPlanDrugOption  
    TextList healthPlanDrugTier  
    TextList healthPlanId  
    URLList healthPlanMarketingUrl  
    stringList usesHealthPlanIdStandard  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

HealthInsurancePlan ||--}o ContactPoint : "contactPoint"
HealthInsurancePlan ||--}o HealthPlanFormulary : "includesHealthPlanFormulary"
HealthInsurancePlan ||--}o HealthPlanNetwork : "includesHealthPlanNetwork"
HealthInsurancePlan ||--}o Action : "potentialAction"

