erDiagram
HealthPlanFormulary {
    BooleanList healthPlanCostSharing  
    TextList healthPlanDrugTier  
    BooleanList offersPrescriptionByMail  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

HealthPlanFormulary ||--}o Action : "potentialAction"

