erDiagram
HowToTool {
    stringList requiredQuantity  
    stringList position  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

HowToTool ||--}o Thing : "item"
HowToTool ||--}o ListItem : "nextItem"
HowToTool ||--}o ListItem : "previousItem"
HowToTool ||--}o Action : "potentialAction"

