erDiagram
HyperToc {
    stringList acquireLicensePage  
    stringList contributor  
    stringList creator  
    stringList dateCreated  
    stringList editEIDR  
    stringList funder  
    stringList genre  
    stringList isPartOf  
    stringList material  
    stringList position  
    stringList publishingPrinciples  
    stringList sponsor  
    stringList usageInfo  
    stringList archivedAt  
    stringList assesses  
    stringList audio  
    stringList author  
    stringList citation  
    stringList contentRating  
    stringList copyrightHolder  
    stringList correction  
    stringList creativeWorkStatus  
    stringList dateModified  
    stringList datePublished  
    stringList educationalLevel  
    stringList educationalUse  
    stringList encodingFormat  
    stringList expires  
    stringList fileFormat  
    stringList inLanguage  
    stringList isBasedOn  
    stringList isBasedOnUrl  
    stringList keywords  
    stringList learningResourceType  
    stringList license  
    stringList maintainer  
    stringList materialExtent  
    stringList offers  
    stringList pattern  
    stringList producer  
    stringList provider  
    stringList publisher  
    stringList schemaVersion  
    stringList sdLicense  
    stringList sdPublisher  
    stringList size  
    stringList teaches  
    stringList temporal  
    stringList temporalCoverage  
    stringList translator  
    stringList version  
    stringList video  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

HyperToc ||--}o HyperTocEntry : "tocEntry"
HyperToc ||--}o MediaObject : "associatedMedia"
HyperToc ||--}o Thing : "about"
HyperToc ||--}o Place : "contentLocation"
HyperToc ||--}o CreativeWork : "hasPart"
HyperToc ||--}o Claim : "interpretedAsClaim"
HyperToc ||--}o Thing : "mainEntity"
HyperToc ||--}o Place : "spatialCoverage"
HyperToc ||--}o CreativeWork : "workExample"
HyperToc ||--}o Text : "abstract"
HyperToc ||--}o Text : "accessMode"
HyperToc ||--}o ItemList : "accessModeSufficient"
HyperToc ||--}o Text : "accessibilityAPI"
HyperToc ||--}o Text : "accessibilityControl"
HyperToc ||--}o Text : "accessibilityFeature"
HyperToc ||--}o Text : "accessibilityHazard"
HyperToc ||--}o Text : "accessibilitySummary"
HyperToc ||--}o Person : "accountablePerson"
HyperToc ||--}o AggregateRating : "aggregateRating"
HyperToc ||--}o Text : "alternativeHeadline"
HyperToc ||--}o Audience : "audience"
HyperToc ||--}o Text : "award"
HyperToc ||--}o Text : "awards"
HyperToc ||--}o Person : "character"
HyperToc ||--}o Comment : "comment"
HyperToc ||--}o Integer : "commentCount"
HyperToc ||--}o Text : "conditionsOfAccess"
HyperToc ||--}o DateTime : "contentReferenceTime"
HyperToc ||--}o Text : "copyrightNotice"
HyperToc ||--}o Number : "copyrightYear"
HyperToc ||--}o Country : "countryOfOrigin"
HyperToc ||--}o Text : "creditText"
HyperToc ||--}o IPTCDigitalSourceEnumeration : "digitalSourceType"
HyperToc ||--}o URL : "discussionUrl"
HyperToc ||--}o Person : "editor"
HyperToc ||--}o AlignmentObject : "educationalAlignment"
HyperToc ||--}o MediaObject : "encoding"
HyperToc ||--}o MediaObject : "encodings"
HyperToc ||--}o CreativeWork : "exampleOfWork"
HyperToc ||--}o Grant : "funding"
HyperToc ||--}o Text : "headline"
HyperToc ||--}o InteractionCounter : "interactionStatistic"
HyperToc ||--}o Text : "interactivityType"
HyperToc ||--}o Boolean : "isAccessibleForFree"
HyperToc ||--}o Boolean : "isFamilyFriendly"
HyperToc ||--}o Place : "locationCreated"
HyperToc ||--}o Thing : "mentions"
HyperToc ||--}o PublicationEvent : "publication"
HyperToc ||--}o Organization : "publisherImprint"
HyperToc ||--}o Event : "recordedAt"
HyperToc ||--}o PublicationEvent : "releasedEvent"
HyperToc ||--}o Review : "review"
HyperToc ||--}o Review : "reviews"
HyperToc ||--}o Date : "sdDatePublished"
HyperToc ||--}o Organization : "sourceOrganization"
HyperToc ||--}o Place : "spatial"
HyperToc ||--}o Text : "text"
HyperToc ||--}o ImageObject : "thumbnail"
HyperToc ||--}o URL : "thumbnailUrl"
HyperToc ||--}o Duration : "timeRequired"
HyperToc ||--}o CreativeWork : "translationOfWork"
HyperToc ||--}o Text : "typicalAgeRange"
HyperToc ||--}o CreativeWork : "workTranslation"
HyperToc ||--}o Text : "alternateName"
HyperToc ||--}o Text : "disambiguatingDescription"
HyperToc ||--}o Text : "name"
HyperToc ||--}o URL : "sameAs"
HyperToc ||--}o Action : "potentialAction"
HyperToc ||--}o URL : "url"

