erDiagram
InfectiousAgentClass {
    stringList supersededBy  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

InfectiousAgentClass ||--}o Text : "alternateName"
InfectiousAgentClass ||--}o Text : "disambiguatingDescription"
InfectiousAgentClass ||--}o Text : "name"
InfectiousAgentClass ||--}o URL : "sameAs"
InfectiousAgentClass ||--}o Action : "potentialAction"
InfectiousAgentClass ||--}o URL : "url"

