erDiagram
InfectiousDisease {
    stringList associatedAnatomy  
    stringList status  
    stringList legalStatus  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

InfectiousDisease ||--}o Text : "infectiousAgent"
InfectiousDisease ||--}o InfectiousAgentClass : "infectiousAgentClass"
InfectiousDisease ||--}o Text : "transmissionMethod"
InfectiousDisease ||--}o DDxElement : "differentialDiagnosis"
InfectiousDisease ||--}o Drug : "drug"
InfectiousDisease ||--}o Text : "epidemiology"
InfectiousDisease ||--}o Text : "expectedPrognosis"
InfectiousDisease ||--}o Text : "naturalProgression"
InfectiousDisease ||--}o Text : "pathophysiology"
InfectiousDisease ||--}o Text : "possibleComplication"
InfectiousDisease ||--}o MedicalTherapy : "possibleTreatment"
InfectiousDisease ||--}o MedicalTherapy : "primaryPrevention"
InfectiousDisease ||--}o MedicalRiskFactor : "riskFactor"
InfectiousDisease ||--}o MedicalTherapy : "secondaryPrevention"
InfectiousDisease ||--}o MedicalSignOrSymptom : "signOrSymptom"
InfectiousDisease ||--}o MedicalConditionStage : "stage"
InfectiousDisease ||--}o MedicalTest : "typicalTest"
InfectiousDisease ||--}o MedicalCode : "code"
InfectiousDisease ||--}o Grant : "funding"
InfectiousDisease ||--}o MedicalGuideline : "guideline"
InfectiousDisease ||--}o MedicineSystem : "medicineSystem"
InfectiousDisease ||--}o Organization : "recognizingAuthority"
InfectiousDisease ||--}o MedicalSpecialty : "relevantSpecialty"
InfectiousDisease ||--}o MedicalStudy : "study"
InfectiousDisease ||--}o Text : "alternateName"
InfectiousDisease ||--}o Text : "disambiguatingDescription"
InfectiousDisease ||--}o Text : "name"
InfectiousDisease ||--}o URL : "sameAs"
InfectiousDisease ||--}o Action : "potentialAction"
InfectiousDisease ||--}o URL : "url"

