erDiagram
JobPosting {
    stringList baseSalary  
    TextList benefits  
    stringList datePosted  
    BooleanList directApply  
    stringList educationRequirements  
    TextList eligibilityToWorkRequirement  
    TextList employerOverview  
    TextList employmentType  
    stringList estimatedSalary  
    BooleanList experienceInPlaceOfEducation  
    stringList experienceRequirements  
    stringList hiringOrganization  
    TextList incentiveCompensation  
    TextList incentives  
    stringList industry  
    TextList jobBenefits  
    BooleanList jobImmediateStart  
    TextList jobLocationType  
    stringList jobStartDate  
    stringList occupationalCategory  
    stringList physicalRequirement  
    stringList qualifications  
    TextList responsibilities  
    TextList salaryCurrency  
    stringList securityClearanceRequirement  
    stringList sensoryRequirement  
    stringList skills  
    TextList specialCommitments  
    TextList title  
    IntegerList totalJobOpenings  
    stringList validThrough  
    TextList workHours  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

JobPosting ||--}o AdministrativeArea : "applicantLocationRequirements"
JobPosting ||--}o ContactPoint : "applicationContact"
JobPosting ||--}o Organization : "employmentUnit"
JobPosting ||--}o Place : "jobLocation"
JobPosting ||--}o Occupation : "relevantOccupation"
JobPosting ||--}o Action : "potentialAction"

