erDiagram
Joint {
    TextList biomechnicalClass  
    stringList functionalClass  
    TextList structuralClass  
    TextList associatedPathophysiology  
    TextList bodyLocation  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Joint ||--}o AnatomicalStructure : "connectedTo"
Joint ||--}o ImageObject : "diagram"
Joint ||--}o AnatomicalSystem : "partOfSystem"
Joint ||--}o MedicalCondition : "relatedCondition"
Joint ||--}o MedicalTherapy : "relatedTherapy"
Joint ||--}o AnatomicalStructure : "subStructure"
Joint ||--}o MedicalCode : "code"
Joint ||--}o Grant : "funding"
Joint ||--}o MedicalGuideline : "guideline"
Joint ||--}o MedicineSystem : "medicineSystem"
Joint ||--}o Organization : "recognizingAuthority"
Joint ||--}o MedicalSpecialty : "relevantSpecialty"
Joint ||--}o MedicalStudy : "study"
Joint ||--}o Action : "potentialAction"

