erDiagram
Language {
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

Language ||--}o Text : "alternateName"
Language ||--}o Text : "disambiguatingDescription"
Language ||--}o Text : "name"
Language ||--}o URL : "sameAs"
Language ||--}o Action : "potentialAction"
Language ||--}o URL : "url"

