erDiagram
LocationFeatureSpecification {
    stringList validFrom  
    stringList validThrough  
    stringList measurementMethod  
    stringList measurementTechnique  
    stringList propertyID  
    stringList unitCode  
    stringList value  
    stringList valueReference  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

LocationFeatureSpecification ||--}o OpeningHoursSpecification : "hoursAvailable"
LocationFeatureSpecification ||--}o Number : "maxValue"
LocationFeatureSpecification ||--}o Number : "minValue"
LocationFeatureSpecification ||--}o Text : "unitText"
LocationFeatureSpecification ||--}o Text : "alternateName"
LocationFeatureSpecification ||--}o Text : "disambiguatingDescription"
LocationFeatureSpecification ||--}o Text : "name"
LocationFeatureSpecification ||--}o URL : "sameAs"
LocationFeatureSpecification ||--}o Action : "potentialAction"
LocationFeatureSpecification ||--}o URL : "url"

