erDiagram
LymphaticVessel {
    stringList regionDrained  
    TextList associatedPathophysiology  
    TextList bodyLocation  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

LymphaticVessel ||--}o Vessel : "originatesFrom"
LymphaticVessel ||--}o Vessel : "runsTo"
LymphaticVessel ||--}o AnatomicalStructure : "connectedTo"
LymphaticVessel ||--}o ImageObject : "diagram"
LymphaticVessel ||--}o AnatomicalSystem : "partOfSystem"
LymphaticVessel ||--}o MedicalCondition : "relatedCondition"
LymphaticVessel ||--}o MedicalTherapy : "relatedTherapy"
LymphaticVessel ||--}o AnatomicalStructure : "subStructure"
LymphaticVessel ||--}o MedicalCode : "code"
LymphaticVessel ||--}o Grant : "funding"
LymphaticVessel ||--}o MedicalGuideline : "guideline"
LymphaticVessel ||--}o MedicineSystem : "medicineSystem"
LymphaticVessel ||--}o Organization : "recognizingAuthority"
LymphaticVessel ||--}o MedicalSpecialty : "relevantSpecialty"
LymphaticVessel ||--}o MedicalStudy : "study"
LymphaticVessel ||--}o Action : "potentialAction"

