erDiagram
MapCategoryType {
    stringList supersededBy  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

MapCategoryType ||--}o Text : "alternateName"
MapCategoryType ||--}o Text : "disambiguatingDescription"
MapCategoryType ||--}o Text : "name"
MapCategoryType ||--}o URL : "sameAs"
MapCategoryType ||--}o Action : "potentialAction"
MapCategoryType ||--}o URL : "url"

