erDiagram
MaximumDoseSchedule {
    TextList frequency  
    TextList doseUnit  
    stringList doseValue  
    TextList targetPopulation  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MaximumDoseSchedule ||--}o MedicalCode : "code"
MaximumDoseSchedule ||--}o Grant : "funding"
MaximumDoseSchedule ||--}o MedicalGuideline : "guideline"
MaximumDoseSchedule ||--}o MedicineSystem : "medicineSystem"
MaximumDoseSchedule ||--}o Organization : "recognizingAuthority"
MaximumDoseSchedule ||--}o MedicalSpecialty : "relevantSpecialty"
MaximumDoseSchedule ||--}o MedicalStudy : "study"
MaximumDoseSchedule ||--}o Action : "potentialAction"

