erDiagram
MedicalProcedure {
    stringList preparation  
    stringList status  
    stringList legalStatus  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

MedicalProcedure ||--}o Text : "bodyLocation"
MedicalProcedure ||--}o Text : "followup"
MedicalProcedure ||--}o Text : "howPerformed"
MedicalProcedure ||--}o MedicalProcedureType : "procedureType"
MedicalProcedure ||--}o MedicalCode : "code"
MedicalProcedure ||--}o Grant : "funding"
MedicalProcedure ||--}o MedicalGuideline : "guideline"
MedicalProcedure ||--}o MedicineSystem : "medicineSystem"
MedicalProcedure ||--}o Organization : "recognizingAuthority"
MedicalProcedure ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalProcedure ||--}o MedicalStudy : "study"
MedicalProcedure ||--}o Text : "alternateName"
MedicalProcedure ||--}o Text : "disambiguatingDescription"
MedicalProcedure ||--}o Text : "name"
MedicalProcedure ||--}o URL : "sameAs"
MedicalProcedure ||--}o Action : "potentialAction"
MedicalProcedure ||--}o URL : "url"

