erDiagram
MedicalGuidelineRecommendation {
    TextList recommendationStrength  
    TextList evidenceOrigin  
    DateList guidelineDate  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalGuidelineRecommendation ||--}o MedicalEvidenceLevel : "evidenceLevel"
MedicalGuidelineRecommendation ||--}o MedicalEntity : "guidelineSubject"
MedicalGuidelineRecommendation ||--}o MedicalCode : "code"
MedicalGuidelineRecommendation ||--}o Grant : "funding"
MedicalGuidelineRecommendation ||--}o MedicalGuideline : "guideline"
MedicalGuidelineRecommendation ||--}o MedicineSystem : "medicineSystem"
MedicalGuidelineRecommendation ||--}o Organization : "recognizingAuthority"
MedicalGuidelineRecommendation ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalGuidelineRecommendation ||--}o MedicalStudy : "study"
MedicalGuidelineRecommendation ||--}o Action : "potentialAction"

