erDiagram
MedicalProcedure {
    TextList bodyLocation  
    TextList followup  
    TextList howPerformed  
    stringList preparation  
    stringList status  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalProcedure ||--}o MedicalProcedureType : "procedureType"
MedicalProcedure ||--}o MedicalCode : "code"
MedicalProcedure ||--}o Grant : "funding"
MedicalProcedure ||--}o MedicalGuideline : "guideline"
MedicalProcedure ||--}o MedicineSystem : "medicineSystem"
MedicalProcedure ||--}o Organization : "recognizingAuthority"
MedicalProcedure ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalProcedure ||--}o MedicalStudy : "study"
MedicalProcedure ||--}o Action : "potentialAction"

