erDiagram
MedicalIntangible {
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalIntangible ||--}o MedicalCode : "code"
MedicalIntangible ||--}o Grant : "funding"
MedicalIntangible ||--}o MedicalGuideline : "guideline"
MedicalIntangible ||--}o MedicineSystem : "medicineSystem"
MedicalIntangible ||--}o Organization : "recognizingAuthority"
MedicalIntangible ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalIntangible ||--}o MedicalStudy : "study"
MedicalIntangible ||--}o Action : "potentialAction"

