erDiagram
MedicalGuideline {
    TextList evidenceOrigin  
    DateList guidelineDate  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalGuideline ||--}o MedicalEvidenceLevel : "evidenceLevel"
MedicalGuideline ||--}o MedicalEntity : "guidelineSubject"
MedicalGuideline ||--}o MedicalCode : "code"
MedicalGuideline ||--}o Grant : "funding"
MedicalGuideline ||--}o MedicalGuideline : "guideline"
MedicalGuideline ||--}o MedicineSystem : "medicineSystem"
MedicalGuideline ||--}o Organization : "recognizingAuthority"
MedicalGuideline ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalGuideline ||--}o MedicalStudy : "study"
MedicalGuideline ||--}o Action : "potentialAction"

