erDiagram
MedicalContraindication {
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalContraindication ||--}o MedicalCode : "code"
MedicalContraindication ||--}o Grant : "funding"
MedicalContraindication ||--}o MedicalGuideline : "guideline"
MedicalContraindication ||--}o MedicineSystem : "medicineSystem"
MedicalContraindication ||--}o Organization : "recognizingAuthority"
MedicalContraindication ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalContraindication ||--}o MedicalStudy : "study"
MedicalContraindication ||--}o Action : "potentialAction"

