erDiagram
MedicalTest {
    stringList normalRange  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalTest ||--}o Drug : "affectedBy"
MedicalTest ||--}o MedicalSign : "signDetected"
MedicalTest ||--}o MedicalCondition : "usedToDiagnose"
MedicalTest ||--}o MedicalDevice : "usesDevice"
MedicalTest ||--}o MedicalCode : "code"
MedicalTest ||--}o Grant : "funding"
MedicalTest ||--}o MedicalGuideline : "guideline"
MedicalTest ||--}o MedicineSystem : "medicineSystem"
MedicalTest ||--}o Organization : "recognizingAuthority"
MedicalTest ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalTest ||--}o MedicalStudy : "study"
MedicalTest ||--}o Action : "potentialAction"

