erDiagram
MedicalGuidelineContraindication {
    TextList evidenceOrigin  
    DateList guidelineDate  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalGuidelineContraindication ||--}o MedicalEvidenceLevel : "evidenceLevel"
MedicalGuidelineContraindication ||--}o MedicalEntity : "guidelineSubject"
MedicalGuidelineContraindication ||--}o MedicalCode : "code"
MedicalGuidelineContraindication ||--}o Grant : "funding"
MedicalGuidelineContraindication ||--}o MedicalGuideline : "guideline"
MedicalGuidelineContraindication ||--}o MedicineSystem : "medicineSystem"
MedicalGuidelineContraindication ||--}o Organization : "recognizingAuthority"
MedicalGuidelineContraindication ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalGuidelineContraindication ||--}o MedicalStudy : "study"
MedicalGuidelineContraindication ||--}o Action : "potentialAction"

