erDiagram
MedicalAudience {
    TextList audienceType  
    TextList requiredGender  
    IntegerList requiredMaxAge  
    IntegerList requiredMinAge  
    stringList suggestedGender  
    NumberList suggestedMaxAge  
    NumberList suggestedMinAge  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalAudience ||--}o AdministrativeArea : "geographicArea"
MedicalAudience ||--}o MedicalCondition : "healthCondition"
MedicalAudience ||--}o QuantitativeValue : "suggestedAge"
MedicalAudience ||--}o QuantitativeValue : "suggestedMeasurement"
MedicalAudience ||--}o Action : "potentialAction"

