erDiagram
MedicalObservationalStudyDesign {
    stringList supersededBy  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

MedicalObservationalStudyDesign ||--}o Text : "alternateName"
MedicalObservationalStudyDesign ||--}o Text : "disambiguatingDescription"
MedicalObservationalStudyDesign ||--}o Text : "name"
MedicalObservationalStudyDesign ||--}o URL : "sameAs"
MedicalObservationalStudyDesign ||--}o Action : "potentialAction"
MedicalObservationalStudyDesign ||--}o URL : "url"

