erDiagram
MedicalObservationalStudy {
    stringList sponsor  
    stringList status  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalObservationalStudy ||--}o MedicalObservationalStudyDesign : "studyDesign"
MedicalObservationalStudy ||--}o MedicalCondition : "healthCondition"
MedicalObservationalStudy ||--}o AdministrativeArea : "studyLocation"
MedicalObservationalStudy ||--}o MedicalEntity : "studySubject"
MedicalObservationalStudy ||--}o MedicalCode : "code"
MedicalObservationalStudy ||--}o Grant : "funding"
MedicalObservationalStudy ||--}o MedicalGuideline : "guideline"
MedicalObservationalStudy ||--}o MedicineSystem : "medicineSystem"
MedicalObservationalStudy ||--}o Organization : "recognizingAuthority"
MedicalObservationalStudy ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalObservationalStudy ||--}o MedicalStudy : "study"
MedicalObservationalStudy ||--}o Action : "potentialAction"

