erDiagram
MedicalRiskFactor {
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalRiskFactor ||--}o MedicalEntity : "increasesRiskOf"
MedicalRiskFactor ||--}o MedicalCode : "code"
MedicalRiskFactor ||--}o Grant : "funding"
MedicalRiskFactor ||--}o MedicalGuideline : "guideline"
MedicalRiskFactor ||--}o MedicineSystem : "medicineSystem"
MedicalRiskFactor ||--}o Organization : "recognizingAuthority"
MedicalRiskFactor ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalRiskFactor ||--}o MedicalStudy : "study"
MedicalRiskFactor ||--}o Action : "potentialAction"

