erDiagram
MedicalRiskCalculator {
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalRiskCalculator ||--}o MedicalEntity : "estimatesRiskOf"
MedicalRiskCalculator ||--}o MedicalRiskFactor : "includedRiskFactor"
MedicalRiskCalculator ||--}o MedicalCode : "code"
MedicalRiskCalculator ||--}o Grant : "funding"
MedicalRiskCalculator ||--}o MedicalGuideline : "guideline"
MedicalRiskCalculator ||--}o MedicineSystem : "medicineSystem"
MedicalRiskCalculator ||--}o Organization : "recognizingAuthority"
MedicalRiskCalculator ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalRiskCalculator ||--}o MedicalStudy : "study"
MedicalRiskCalculator ||--}o Action : "potentialAction"

