erDiagram
MediaSubscription {
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MediaSubscription ||--}o Organization : "authenticator"
MediaSubscription ||--}o Offer : "expectsAcceptanceOf"
MediaSubscription ||--}o Action : "potentialAction"

