erDiagram
MedicalEntity {
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalEntity ||--}o MedicalCode : "code"
MedicalEntity ||--}o Grant : "funding"
MedicalEntity ||--}o MedicalGuideline : "guideline"
MedicalEntity ||--}o MedicineSystem : "medicineSystem"
MedicalEntity ||--}o Organization : "recognizingAuthority"
MedicalEntity ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalEntity ||--}o MedicalStudy : "study"
MedicalEntity ||--}o Action : "potentialAction"

