erDiagram
MedicalConditionStage {
    stringList legalStatus  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

MedicalConditionStage ||--}o Number : "stageAsNumber"
MedicalConditionStage ||--}o Text : "subStageSuffix"
MedicalConditionStage ||--}o MedicalCode : "code"
MedicalConditionStage ||--}o Grant : "funding"
MedicalConditionStage ||--}o MedicalGuideline : "guideline"
MedicalConditionStage ||--}o MedicineSystem : "medicineSystem"
MedicalConditionStage ||--}o Organization : "recognizingAuthority"
MedicalConditionStage ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalConditionStage ||--}o MedicalStudy : "study"
MedicalConditionStage ||--}o Text : "alternateName"
MedicalConditionStage ||--}o Text : "disambiguatingDescription"
MedicalConditionStage ||--}o Text : "name"
MedicalConditionStage ||--}o URL : "sameAs"
MedicalConditionStage ||--}o Action : "potentialAction"
MedicalConditionStage ||--}o URL : "url"

