erDiagram
MedicalDevice {
    stringList contraindication  
    TextList postOp  
    TextList preOp  
    TextList procedure  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalDevice ||--}o MedicalEntity : "adverseOutcome"
MedicalDevice ||--}o MedicalEntity : "seriousAdverseOutcome"
MedicalDevice ||--}o MedicalCode : "code"
MedicalDevice ||--}o Grant : "funding"
MedicalDevice ||--}o MedicalGuideline : "guideline"
MedicalDevice ||--}o MedicineSystem : "medicineSystem"
MedicalDevice ||--}o Organization : "recognizingAuthority"
MedicalDevice ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalDevice ||--}o MedicalStudy : "study"
MedicalDevice ||--}o Action : "potentialAction"

