erDiagram
MedicalRiskEstimator {
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MedicalRiskEstimator ||--}o MedicalEntity : "estimatesRiskOf"
MedicalRiskEstimator ||--}o MedicalRiskFactor : "includedRiskFactor"
MedicalRiskEstimator ||--}o MedicalCode : "code"
MedicalRiskEstimator ||--}o Grant : "funding"
MedicalRiskEstimator ||--}o MedicalGuideline : "guideline"
MedicalRiskEstimator ||--}o MedicineSystem : "medicineSystem"
MedicalRiskEstimator ||--}o Organization : "recognizingAuthority"
MedicalRiskEstimator ||--}o MedicalSpecialty : "relevantSpecialty"
MedicalRiskEstimator ||--}o MedicalStudy : "study"
MedicalRiskEstimator ||--}o Action : "potentialAction"

