erDiagram
MemberProgramTier {
    stringList hasTierRequirement  
    stringList membershipPointsEarned  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MemberProgramTier ||--}o TierBenefitEnumeration : "hasTierBenefit"
MemberProgramTier ||--}o MemberProgram : "isTierOf"
MemberProgramTier ||--}o Action : "potentialAction"

