erDiagram
MemberProgram {
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MemberProgram ||--}o MemberProgramTier : "hasTiers"
MemberProgram ||--}o Organization : "hostingOrganization"
MemberProgram ||--}o Action : "potentialAction"

