erDiagram
MenuItem {
    stringList menuAddOn  
    stringList offers  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MenuItem ||--}o NutritionInformation : "nutrition"
MenuItem ||--}o RestrictedDiet : "suitableForDiet"
MenuItem ||--}o Action : "potentialAction"

