erDiagram
MerchantReturnPolicySeasonalOverride {
    stringList endDate  
    stringList merchantReturnDays  
    stringList restockingFee  
    stringList startDate  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MerchantReturnPolicySeasonalOverride ||--}o RefundTypeEnumeration : "refundType"
MerchantReturnPolicySeasonalOverride ||--}o ReturnFeesEnumeration : "returnFees"
MerchantReturnPolicySeasonalOverride ||--}o ReturnMethodEnumeration : "returnMethod"
MerchantReturnPolicySeasonalOverride ||--}o MerchantReturnEnumeration : "returnPolicyCategory"
MerchantReturnPolicySeasonalOverride ||--}o MonetaryAmount : "returnShippingFeesAmount"
MerchantReturnPolicySeasonalOverride ||--}o Action : "potentialAction"

