erDiagram
MerchantReturnPolicy {
    stringList applicableCountry  
    BooleanList inStoreReturnsOffered  
    stringList merchantReturnDays  
    URLList merchantReturnLink  
    stringList restockingFee  
    stringList returnPolicyCountry  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MerchantReturnPolicy ||--}o PropertyValue : "additionalProperty"
MerchantReturnPolicy ||--}o ReturnFeesEnumeration : "customerRemorseReturnFees"
MerchantReturnPolicy ||--}o ReturnLabelSourceEnumeration : "customerRemorseReturnLabelSource"
MerchantReturnPolicy ||--}o MonetaryAmount : "customerRemorseReturnShippingFeesAmount"
MerchantReturnPolicy ||--}o OfferItemCondition : "itemCondition"
MerchantReturnPolicy ||--}o ReturnFeesEnumeration : "itemDefectReturnFees"
MerchantReturnPolicy ||--}o ReturnLabelSourceEnumeration : "itemDefectReturnLabelSource"
MerchantReturnPolicy ||--}o MonetaryAmount : "itemDefectReturnShippingFeesAmount"
MerchantReturnPolicy ||--}o RefundTypeEnumeration : "refundType"
MerchantReturnPolicy ||--}o ReturnFeesEnumeration : "returnFees"
MerchantReturnPolicy ||--}o ReturnLabelSourceEnumeration : "returnLabelSource"
MerchantReturnPolicy ||--}o ReturnMethodEnumeration : "returnMethod"
MerchantReturnPolicy ||--}o MerchantReturnEnumeration : "returnPolicyCategory"
MerchantReturnPolicy ||--}o MerchantReturnPolicySeasonalOverride : "returnPolicySeasonalOverride"
MerchantReturnPolicy ||--}o MonetaryAmount : "returnShippingFeesAmount"
MerchantReturnPolicy ||--}o MemberProgramTier : "validForMemberTier"
MerchantReturnPolicy ||--}o Action : "potentialAction"

