erDiagram
MonetaryAmount {
    TextList currency  
    NumberList maxValue  
    NumberList minValue  
    stringList validFrom  
    stringList validThrough  
    stringList value  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MonetaryAmount ||--}o Action : "potentialAction"

