erDiagram
MonetaryAmountDistribution {
    TextList currency  
    NumberList median  
    NumberList percentile10  
    NumberList percentile25  
    NumberList percentile75  
    NumberList percentile90  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

MonetaryAmountDistribution ||--}o Duration : "duration"
MonetaryAmountDistribution ||--}o Action : "potentialAction"

