erDiagram
Muscle {
    stringList legalStatus  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

Muscle ||--}o Muscle : "antagonist"
Muscle ||--}o Vessel : "bloodSupply"
Muscle ||--}o AnatomicalStructure : "insertion"
Muscle ||--}o Text : "muscleAction"
Muscle ||--}o Nerve : "nerve"
Muscle ||--}o Text : "associatedPathophysiology"
Muscle ||--}o Text : "bodyLocation"
Muscle ||--}o AnatomicalStructure : "connectedTo"
Muscle ||--}o ImageObject : "diagram"
Muscle ||--}o AnatomicalSystem : "partOfSystem"
Muscle ||--}o MedicalCondition : "relatedCondition"
Muscle ||--}o MedicalTherapy : "relatedTherapy"
Muscle ||--}o AnatomicalStructure : "subStructure"
Muscle ||--}o MedicalCode : "code"
Muscle ||--}o Grant : "funding"
Muscle ||--}o MedicalGuideline : "guideline"
Muscle ||--}o MedicineSystem : "medicineSystem"
Muscle ||--}o Organization : "recognizingAuthority"
Muscle ||--}o MedicalSpecialty : "relevantSpecialty"
Muscle ||--}o MedicalStudy : "study"
Muscle ||--}o Text : "alternateName"
Muscle ||--}o Text : "disambiguatingDescription"
Muscle ||--}o Text : "name"
Muscle ||--}o URL : "sameAs"
Muscle ||--}o Action : "potentialAction"
Muscle ||--}o URL : "url"

