erDiagram
Nerve {
    stringList sensoryUnit  
    TextList associatedPathophysiology  
    TextList bodyLocation  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Nerve ||--}o AnatomicalStructure : "branch"
Nerve ||--}o Muscle : "nerveMotor"
Nerve ||--}o BrainStructure : "sourcedFrom"
Nerve ||--}o AnatomicalStructure : "connectedTo"
Nerve ||--}o ImageObject : "diagram"
Nerve ||--}o AnatomicalSystem : "partOfSystem"
Nerve ||--}o MedicalCondition : "relatedCondition"
Nerve ||--}o MedicalTherapy : "relatedTherapy"
Nerve ||--}o AnatomicalStructure : "subStructure"
Nerve ||--}o MedicalCode : "code"
Nerve ||--}o Grant : "funding"
Nerve ||--}o MedicalGuideline : "guideline"
Nerve ||--}o MedicineSystem : "medicineSystem"
Nerve ||--}o Organization : "recognizingAuthority"
Nerve ||--}o MedicalSpecialty : "relevantSpecialty"
Nerve ||--}o MedicalStudy : "study"
Nerve ||--}o Action : "potentialAction"

