erDiagram
Observation {
    stringList measurementMethod  
    stringList measurementTechnique  
    stringList observationAbout  
    DateTimeList observationDate  
    TextList observationPeriod  
    stringList variableMeasured  
    NumberList maxValue  
    NumberList minValue  
    stringList unitCode  
    TextList unitText  
    stringList value  
    stringList valueReference  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Observation ||--}o QuantitativeValue : "marginOfError"
Observation ||--}o Property : "measuredProperty"
Observation ||--}o StatisticalVariable : "measurementDenominator"
Observation ||--}o Enumeration : "measurementQualifier"
Observation ||--}o PropertyValue : "additionalProperty"
Observation ||--}o Action : "potentialAction"

