erDiagram
Occupation {
    stringList educationRequirements  
    stringList estimatedSalary  
    stringList experienceRequirements  
    stringList occupationalCategory  
    stringList qualifications  
    TextList responsibilities  
    stringList skills  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Occupation ||--}o AdministrativeArea : "occupationLocation"
Occupation ||--}o Action : "potentialAction"

