erDiagram
OccupationalExperienceRequirements {
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

OccupationalExperienceRequirements ||--}o Number : "monthsOfExperience"
OccupationalExperienceRequirements ||--}o Text : "alternateName"
OccupationalExperienceRequirements ||--}o Text : "disambiguatingDescription"
OccupationalExperienceRequirements ||--}o Text : "name"
OccupationalExperienceRequirements ||--}o URL : "sameAs"
OccupationalExperienceRequirements ||--}o Action : "potentialAction"
OccupationalExperienceRequirements ||--}o URL : "url"

