erDiagram
OfferCatalog {
    stringList itemListElement  
    stringList itemListOrder  
    IntegerList numberOfItems  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

OfferCatalog ||--}o Action : "potentialAction"

