erDiagram
OpeningHoursSpecification {
    TimeList closes  
    TimeList opens  
    stringList validFrom  
    stringList validThrough  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

OpeningHoursSpecification ||--}o DayOfWeek : "dayOfWeek"
OpeningHoursSpecification ||--}o Action : "potentialAction"

