erDiagram
OrderItem {
    TextList orderItemNumber  
    stringList orderQuantity  
    stringList orderedItem  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

OrderItem ||--}o ParcelDelivery : "orderDelivery"
OrderItem ||--}o OrderStatus : "orderItemStatus"
OrderItem ||--}o Action : "potentialAction"

