erDiagram
Order {
    TextList confirmationNumber  
    TextList orderNumber  
    stringList seller  
    stringList broker  
    stringList customer  
    stringList discount  
    TextList discountCode  
    TextList discountCurrency  
    BooleanList isGift  
    stringList merchant  
    stringList orderDate  
    stringList orderedItem  
    DateTimeList paymentDue  
    stringList paymentDueDate  
    stringList paymentMethod  
    TextList paymentMethodId  
    URLList paymentUrl  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Order ||--}o Offer : "acceptedOffer"
Order ||--}o PostalAddress : "billingAddress"
Order ||--}o ParcelDelivery : "orderDelivery"
Order ||--}o OrderStatus : "orderStatus"
Order ||--}o Invoice : "partOfInvoice"
Order ||--}o Action : "potentialAction"

