erDiagram
ParcelDelivery {
    stringList expectedArrivalFrom  
    stringList expectedArrivalUntil  
    stringList provider  
    TextList trackingNumber  
    URLList trackingUrl  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

ParcelDelivery ||--}o Organization : "carrier"
ParcelDelivery ||--}o PostalAddress : "deliveryAddress"
ParcelDelivery ||--}o DeliveryEvent : "deliveryStatus"
ParcelDelivery ||--}o DeliveryMethod : "hasDeliveryMethod"
ParcelDelivery ||--}o Product : "itemShipped"
ParcelDelivery ||--}o PostalAddress : "originAddress"
ParcelDelivery ||--}o Order : "partOfOrder"
ParcelDelivery ||--}o Action : "potentialAction"

