erDiagram
PayAction {
    stringList recipient  
    stringList price  
    stringList location  
    stringList participant  
    stringList agent  
    stringList endTime  
    stringList provider  
    stringList startTime  
    stringList target  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

PayAction ||--}o Text : "priceCurrency"
PayAction ||--}o PriceSpecification : "priceSpecification"
PayAction ||--}o Thing : "instrument"
PayAction ||--}o Thing : "object"
PayAction ||--}o Thing : "result"
PayAction ||--}o HowTo : "actionProcess"
PayAction ||--}o ActionStatusType : "actionStatus"
PayAction ||--}o Thing : "error"
PayAction ||--}o Text : "alternateName"
PayAction ||--}o Text : "disambiguatingDescription"
PayAction ||--}o Text : "name"
PayAction ||--}o URL : "sameAs"
PayAction ||--}o Action : "potentialAction"
PayAction ||--}o URL : "url"

