erDiagram
PaymentChargeSpecification {
    NumberList maxPrice  
    stringList membershipPointsEarned  
    NumberList minPrice  
    stringList price  
    TextList priceCurrency  
    stringList validFrom  
    stringList validThrough  
    BooleanList valueAddedTaxIncluded  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

PaymentChargeSpecification ||--}o DeliveryMethod : "appliesToDeliveryMethod"
PaymentChargeSpecification ||--}o PaymentMethod : "appliesToPaymentMethod"
PaymentChargeSpecification ||--}o QuantitativeValue : "eligibleQuantity"
PaymentChargeSpecification ||--}o PriceSpecification : "eligibleTransactionVolume"
PaymentChargeSpecification ||--}o MemberProgramTier : "validForMemberTier"
PaymentChargeSpecification ||--}o Action : "potentialAction"

