erDiagram
Permit {
    stringList validFrom  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

Permit ||--}o Organization : "issuedBy"
Permit ||--}o Service : "issuedThrough"
Permit ||--}o Audience : "permitAudience"
Permit ||--}o Duration : "validFor"
Permit ||--}o AdministrativeArea : "validIn"
Permit ||--}o Date : "validUntil"
Permit ||--}o Text : "alternateName"
Permit ||--}o Text : "disambiguatingDescription"
Permit ||--}o Text : "name"
Permit ||--}o URL : "sameAs"
Permit ||--}o Action : "potentialAction"
Permit ||--}o URL : "url"

