erDiagram
Person {
    TextList additionalName  
    TextList callSign  
    TextList duns  
    stringList funder  
    TextList globalLocationNumber  
    stringList homeLocation  
    stringList memberOf  
    stringList publishingPrinciples  
    stringList sponsor  
    TextList taxID  
    stringList workLocation  
    stringList address  
    stringList alumniOf  
    TextList award  
    TextList awards  
    DateList birthDate  
    stringList brand  
    stringList colleague  
    DateList deathDate  
    TextList email  
    TextList familyName  
    TextList faxNumber  
    stringList gender  
    TextList givenName  
    stringList height  
    TextList honorificPrefix  
    TextList honorificSuffix  
    TextList isicV4  
    stringList jobTitle  
    stringList knowsAbout  
    stringList knowsLanguage  
    TextList naics  
    stringList netWorth  
    stringList owns  
    stringList skills  
    TextList telephone  
    TextList vatID  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Person ||--}o Organization : "affiliation"
Person ||--}o InteractionCounter : "agentInteractionStatistic"
Person ||--}o Place : "birthPlace"
Person ||--}o Person : "children"
Person ||--}o Person : "colleagues"
Person ||--}o ContactPoint : "contactPoint"
Person ||--}o ContactPoint : "contactPoints"
Person ||--}o Place : "deathPlace"
Person ||--}o Person : "follows"
Person ||--}o Grant : "funding"
Person ||--}o Certification : "hasCertification"
Person ||--}o EducationalOccupationalCredential : "hasCredential"
Person ||--}o Occupation : "hasOccupation"
Person ||--}o OfferCatalog : "hasOfferCatalog"
Person ||--}o Place : "hasPOS"
Person ||--}o InteractionCounter : "interactionStatistic"
Person ||--}o Person : "knows"
Person ||--}o Offer : "makesOffer"
Person ||--}o Country : "nationality"
Person ||--}o Person : "parent"
Person ||--}o Person : "parents"
Person ||--}o Event : "performerIn"
Person ||--}o Person : "relatedTo"
Person ||--}o Demand : "seeks"
Person ||--}o Person : "sibling"
Person ||--}o Person : "siblings"
Person ||--}o Person : "spouse"
Person ||--}o QuantitativeValue : "weight"
Person ||--}o Organization : "worksFor"
Person ||--}o Action : "potentialAction"

