erDiagram
PhysicalActivity {
    stringList category  
    stringList associatedAnatomy  
    TextList epidemiology  
    TextList pathophysiology  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

PhysicalActivity ||--}o MedicalCode : "code"
PhysicalActivity ||--}o Grant : "funding"
PhysicalActivity ||--}o MedicalGuideline : "guideline"
PhysicalActivity ||--}o MedicineSystem : "medicineSystem"
PhysicalActivity ||--}o Organization : "recognizingAuthority"
PhysicalActivity ||--}o MedicalSpecialty : "relevantSpecialty"
PhysicalActivity ||--}o MedicalStudy : "study"
PhysicalActivity ||--}o Action : "potentialAction"

