erDiagram
ProductCollection {
    IntegerList collectionSize  
    stringList asin  
    stringList category  
    stringList colorSwatch  
    stringList gtin  
    TextList gtin12  
    TextList gtin13  
    TextList gtin14  
    TextList gtin8  
    URLList hasGS1DigitalLink  
    stringList logo  
    stringList material  
    TextList nsn  
    TextList productID  
    TextList sku  
    TextList award  
    TextList awards  
    stringList brand  
    TextList color  
    TextList countryOfAssembly  
    TextList countryOfLastProcessing  
    stringList depth  
    stringList height  
    TextList inProductGroupWithID  
    BooleanList isFamilyFriendly  
    stringList isRelatedTo  
    stringList isSimilarTo  
    stringList isVariantOf  
    stringList keywords  
    TextList mobileUrl  
    stringList model  
    TextList mpn  
    stringList negativeNotes  
    stringList offers  
    stringList pattern  
    stringList positiveNotes  
    DateList productionDate  
    DateList purchaseDate  
    DateList releaseDate  
    stringList size  
    TextList slogan  
    stringList width  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
    stringList acquireLicensePage  
    stringList contributor  
    stringList creator  
    stringList dateCreated  
    stringList editEIDR  
    stringList funder  
    stringList genre  
    stringList isPartOf  
    stringList position  
    stringList publishingPrinciples  
    stringList sponsor  
    stringList usageInfo  
    TextList abstract  
    TextList accessMode  
    TextList accessibilityAPI  
    TextList accessibilityControl  
    TextList accessibilityFeature  
    TextList accessibilityHazard  
    TextList accessibilitySummary  
    TextList alternativeHeadline  
    stringList archivedAt  
    stringList assesses  
    stringList audio  
    stringList author  
    stringList citation  
    IntegerList commentCount  
    TextList conditionsOfAccess  
    stringList contentRating  
    DateTimeList contentReferenceTime  
    stringList copyrightHolder  
    TextList copyrightNotice  
    NumberList copyrightYear  
    stringList correction  
    stringList creativeWorkStatus  
    TextList creditText  
    stringList dateModified  
    stringList datePublished  
    URLList discussionUrl  
    stringList educationalLevel  
    stringList educationalUse  
    stringList encodingFormat  
    stringList expires  
    stringList fileFormat  
    TextList headline  
    stringList inLanguage  
    TextList interactivityType  
    BooleanList isAccessibleForFree  
    stringList isBasedOn  
    stringList isBasedOnUrl  
    stringList learningResourceType  
    stringList license  
    stringList maintainer  
    stringList materialExtent  
    stringList producer  
    stringList provider  
    stringList publisher  
    stringList schemaVersion  
    DateList sdDatePublished  
    stringList sdLicense  
    stringList sdPublisher  
    stringList teaches  
    stringList temporal  
    stringList temporalCoverage  
    TextList text  
    URLList thumbnailUrl  
    stringList translator  
    TextList typicalAgeRange  
    stringList version  
    stringList video  
}

ProductCollection ||--}o TypeAndQuantityNode : "includesObject"
ProductCollection ||--}o PropertyValue : "additionalProperty"
ProductCollection ||--}o AggregateRating : "aggregateRating"
ProductCollection ||--}o Audience : "audience"
ProductCollection ||--}o Country : "countryOfOrigin"
ProductCollection ||--}o Grant : "funding"
ProductCollection ||--}o AdultOrientedEnumeration : "hasAdultConsideration"
ProductCollection ||--}o Certification : "hasCertification"
ProductCollection ||--}o EnergyConsumptionDetails : "hasEnergyConsumptionDetails"
ProductCollection ||--}o QuantitativeValue : "hasMeasurement"
ProductCollection ||--}o MerchantReturnPolicy : "hasMerchantReturnPolicy"
ProductCollection ||--}o Product : "isAccessoryOrSparePartFor"
ProductCollection ||--}o Product : "isConsumableFor"
ProductCollection ||--}o OfferItemCondition : "itemCondition"
ProductCollection ||--}o Organization : "manufacturer"
ProductCollection ||--}o Review : "review"
ProductCollection ||--}o Review : "reviews"
ProductCollection ||--}o QuantitativeValue : "weight"
ProductCollection ||--}o Action : "potentialAction"
ProductCollection ||--}o Thing : "about"
ProductCollection ||--}o Place : "contentLocation"
ProductCollection ||--}o CreativeWork : "hasPart"
ProductCollection ||--}o Claim : "interpretedAsClaim"
ProductCollection ||--}o Thing : "mainEntity"
ProductCollection ||--}o Place : "spatialCoverage"
ProductCollection ||--}o CreativeWork : "workExample"
ProductCollection ||--}o ItemList : "accessModeSufficient"
ProductCollection ||--}o Person : "accountablePerson"
ProductCollection ||--}o MediaObject : "associatedMedia"
ProductCollection ||--}o Person : "character"
ProductCollection ||--}o Comment : "comment"
ProductCollection ||--}o IPTCDigitalSourceEnumeration : "digitalSourceType"
ProductCollection ||--}o Person : "editor"
ProductCollection ||--}o AlignmentObject : "educationalAlignment"
ProductCollection ||--}o MediaObject : "encoding"
ProductCollection ||--}o MediaObject : "encodings"
ProductCollection ||--}o CreativeWork : "exampleOfWork"
ProductCollection ||--}o InteractionCounter : "interactionStatistic"
ProductCollection ||--}o Place : "locationCreated"
ProductCollection ||--}o Thing : "mentions"
ProductCollection ||--}o PublicationEvent : "publication"
ProductCollection ||--}o Organization : "publisherImprint"
ProductCollection ||--}o Event : "recordedAt"
ProductCollection ||--}o PublicationEvent : "releasedEvent"
ProductCollection ||--}o Organization : "sourceOrganization"
ProductCollection ||--}o Place : "spatial"
ProductCollection ||--}o ImageObject : "thumbnail"
ProductCollection ||--}o Duration : "timeRequired"
ProductCollection ||--}o CreativeWork : "translationOfWork"
ProductCollection ||--}o CreativeWork : "workTranslation"

