erDiagram
ProgramMembership {
    stringList member  
    stringList members  
    TextList membershipNumber  
    stringList membershipPointsEarned  
    TextList programName  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

ProgramMembership ||--}o Organization : "hostingOrganization"
ProgramMembership ||--}o MemberProgram : "program"
ProgramMembership ||--}o Action : "potentialAction"

