erDiagram
Property {
    stringList supersededBy  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

Property ||--}o Class : "domainIncludes"
Property ||--}o Property : "inverseOf"
Property ||--}o Class : "rangeIncludes"
Property ||--}o Text : "alternateName"
Property ||--}o Text : "disambiguatingDescription"
Property ||--}o Text : "name"
Property ||--}o URL : "sameAs"
Property ||--}o Action : "potentialAction"
Property ||--}o URL : "url"

