erDiagram
PropertyValueSpecification {
    stringList defaultValue  
    NumberList maxValue  
    NumberList minValue  
    BooleanList multipleValues  
    BooleanList readonlyValue  
    NumberList stepValue  
    NumberList valueMaxLength  
    NumberList valueMinLength  
    TextList valueName  
    TextList valuePattern  
    BooleanList valueRequired  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

PropertyValueSpecification ||--}o Action : "potentialAction"

