erDiagram
PropertyValueSpecification {
    stringList defaultValue  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

PropertyValueSpecification ||--}o Number : "maxValue"
PropertyValueSpecification ||--}o Number : "minValue"
PropertyValueSpecification ||--}o Boolean : "multipleValues"
PropertyValueSpecification ||--}o Boolean : "readonlyValue"
PropertyValueSpecification ||--}o Number : "stepValue"
PropertyValueSpecification ||--}o Number : "valueMaxLength"
PropertyValueSpecification ||--}o Number : "valueMinLength"
PropertyValueSpecification ||--}o Text : "valueName"
PropertyValueSpecification ||--}o Text : "valuePattern"
PropertyValueSpecification ||--}o Boolean : "valueRequired"
PropertyValueSpecification ||--}o Text : "alternateName"
PropertyValueSpecification ||--}o Text : "disambiguatingDescription"
PropertyValueSpecification ||--}o Text : "name"
PropertyValueSpecification ||--}o URL : "sameAs"
PropertyValueSpecification ||--}o Action : "potentialAction"
PropertyValueSpecification ||--}o URL : "url"

