erDiagram
Protein {
    TextList hasBioPolymerSequence  
    stringList hasRepresentation  
    stringList associatedDisease  
    stringList hasMolecularFunction  
    stringList isInvolvedInBiologicalProcess  
    stringList isLocatedInSubcellularLocation  
    stringList taxonomicRange  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Protein ||--}o BioChemEntity : "bioChemInteraction"
Protein ||--}o BioChemEntity : "bioChemSimilarity"
Protein ||--}o DefinedTerm : "biologicalRole"
Protein ||--}o Grant : "funding"
Protein ||--}o BioChemEntity : "hasBioChemEntityPart"
Protein ||--}o Gene : "isEncodedByBioChemEntity"
Protein ||--}o BioChemEntity : "isPartOfBioChemEntity"
Protein ||--}o Action : "potentialAction"

