erDiagram
PublicToilet {
    TextList openingHours  
    TextList globalLocationNumber  
    URLList hasGS1DigitalLink  
    stringList logo  
    stringList photo  
    stringList address  
    TextList branchCode  
    TextList faxNumber  
    stringList geo  
    stringList geoContains  
    stringList geoCoveredBy  
    stringList geoCovers  
    stringList geoCrosses  
    stringList geoDisjoint  
    stringList geoEquals  
    stringList geoIntersects  
    stringList geoOverlaps  
    stringList geoTouches  
    stringList geoWithin  
    BooleanList hasDriveThroughService  
    stringList hasMap  
    BooleanList isAccessibleForFree  
    TextList isicV4  
    stringList keywords  
    stringList latitude  
    stringList longitude  
    URLList map  
    URLList maps  
    IntegerList maximumAttendeeCapacity  
    stringList photos  
    BooleanList publicAccess  
    TextList slogan  
    BooleanList smokingAllowed  
    TextList telephone  
    URLList tourBookingPage  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

PublicToilet ||--}o PropertyValue : "additionalProperty"
PublicToilet ||--}o AggregateRating : "aggregateRating"
PublicToilet ||--}o LocationFeatureSpecification : "amenityFeature"
PublicToilet ||--}o Place : "containedIn"
PublicToilet ||--}o Place : "containedInPlace"
PublicToilet ||--}o Place : "containsPlace"
PublicToilet ||--}o Event : "event"
PublicToilet ||--}o Event : "events"
PublicToilet ||--}o Certification : "hasCertification"
PublicToilet ||--}o OpeningHoursSpecification : "openingHoursSpecification"
PublicToilet ||--}o Review : "review"
PublicToilet ||--}o Review : "reviews"
PublicToilet ||--}o OpeningHoursSpecification : "specialOpeningHoursSpecification"
PublicToilet ||--}o Action : "potentialAction"

