erDiagram
QuantitativeValue {
    NumberList maxValue  
    NumberList minValue  
    stringList unitCode  
    TextList unitText  
    stringList value  
    stringList valueReference  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

QuantitativeValue ||--}o PropertyValue : "additionalProperty"
QuantitativeValue ||--}o Action : "potentialAction"

