erDiagram
QuantitativeValue {
    stringList unitCode  
    stringList value  
    stringList valueReference  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

QuantitativeValue ||--}o PropertyValue : "additionalProperty"
QuantitativeValue ||--}o Number : "maxValue"
QuantitativeValue ||--}o Number : "minValue"
QuantitativeValue ||--}o Text : "unitText"
QuantitativeValue ||--}o Text : "alternateName"
QuantitativeValue ||--}o Text : "disambiguatingDescription"
QuantitativeValue ||--}o Text : "name"
QuantitativeValue ||--}o URL : "sameAs"
QuantitativeValue ||--}o Action : "potentialAction"
QuantitativeValue ||--}o URL : "url"

