erDiagram
RentalCarReservation {
    stringList bookingAgent  
    stringList broker  
    stringList provider  
    stringList totalPrice  
    stringList underName  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

RentalCarReservation ||--}o Place : "dropoffLocation"
RentalCarReservation ||--}o DateTime : "dropoffTime"
RentalCarReservation ||--}o Place : "pickupLocation"
RentalCarReservation ||--}o DateTime : "pickupTime"
RentalCarReservation ||--}o DateTime : "bookingTime"
RentalCarReservation ||--}o DateTime : "modifiedTime"
RentalCarReservation ||--}o Text : "priceCurrency"
RentalCarReservation ||--}o ProgramMembership : "programMembershipUsed"
RentalCarReservation ||--}o Thing : "reservationFor"
RentalCarReservation ||--}o Text : "reservationId"
RentalCarReservation ||--}o ReservationStatusType : "reservationStatus"
RentalCarReservation ||--}o Ticket : "reservedTicket"
RentalCarReservation ||--}o Text : "alternateName"
RentalCarReservation ||--}o Text : "disambiguatingDescription"
RentalCarReservation ||--}o Text : "name"
RentalCarReservation ||--}o URL : "sameAs"
RentalCarReservation ||--}o Action : "potentialAction"
RentalCarReservation ||--}o URL : "url"

