erDiagram
RepaymentSpecification {
    stringList downPayment  
    NumberList loanPaymentFrequency  
    NumberList numberOfLoanPayments  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

RepaymentSpecification ||--}o MonetaryAmount : "earlyPrepaymentPenalty"
RepaymentSpecification ||--}o MonetaryAmount : "loanPaymentAmount"
RepaymentSpecification ||--}o Action : "potentialAction"

