erDiagram
ReportedDoseSchedule {
    stringList doseValue  
    stringList legalStatus  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

ReportedDoseSchedule ||--}o Text : "frequency"
ReportedDoseSchedule ||--}o Text : "doseUnit"
ReportedDoseSchedule ||--}o Text : "targetPopulation"
ReportedDoseSchedule ||--}o MedicalCode : "code"
ReportedDoseSchedule ||--}o Grant : "funding"
ReportedDoseSchedule ||--}o MedicalGuideline : "guideline"
ReportedDoseSchedule ||--}o MedicineSystem : "medicineSystem"
ReportedDoseSchedule ||--}o Organization : "recognizingAuthority"
ReportedDoseSchedule ||--}o MedicalSpecialty : "relevantSpecialty"
ReportedDoseSchedule ||--}o MedicalStudy : "study"
ReportedDoseSchedule ||--}o Text : "alternateName"
ReportedDoseSchedule ||--}o Text : "disambiguatingDescription"
ReportedDoseSchedule ||--}o Text : "name"
ReportedDoseSchedule ||--}o URL : "sameAs"
ReportedDoseSchedule ||--}o Action : "potentialAction"
ReportedDoseSchedule ||--}o URL : "url"

