erDiagram
ReservationStatusType {
    stringList supersededBy  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

ReservationStatusType ||--}o Action : "potentialAction"

