erDiagram
ReturnFeesEnumeration {
    stringList supersededBy  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

ReturnFeesEnumeration ||--}o Text : "alternateName"
ReturnFeesEnumeration ||--}o Text : "disambiguatingDescription"
ReturnFeesEnumeration ||--}o Text : "name"
ReturnFeesEnumeration ||--}o URL : "sameAs"
ReturnFeesEnumeration ||--}o Action : "potentialAction"
ReturnFeesEnumeration ||--}o URL : "url"

