erDiagram
ReturnLabelSourceEnumeration {
    stringList supersededBy  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

ReturnLabelSourceEnumeration ||--}o Text : "alternateName"
ReturnLabelSourceEnumeration ||--}o Text : "disambiguatingDescription"
ReturnLabelSourceEnumeration ||--}o Text : "name"
ReturnLabelSourceEnumeration ||--}o URL : "sameAs"
ReturnLabelSourceEnumeration ||--}o Action : "potentialAction"
ReturnLabelSourceEnumeration ||--}o URL : "url"

