erDiagram
Role {
    stringList endDate  
    stringList namedPosition  
    stringList roleName  
    stringList startDate  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

Role ||--}o Text : "alternateName"
Role ||--}o Text : "disambiguatingDescription"
Role ||--}o Text : "name"
Role ||--}o URL : "sameAs"
Role ||--}o Action : "potentialAction"
Role ||--}o URL : "url"

