erDiagram
Role {
    stringList endDate  
    stringList namedPosition  
    stringList roleName  
    stringList startDate  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Role ||--}o Action : "potentialAction"

