erDiagram
Schedule {
    TextList repeatFrequency  
    stringList byDay  
    IntegerList byMonth  
    IntegerList byMonthDay  
    IntegerList byMonthWeek  
    stringList endDate  
    stringList endTime  
    stringList exceptDate  
    IntegerList repeatCount  
    TextList scheduleTimezone  
    stringList startDate  
    stringList startTime  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Schedule ||--}o Duration : "duration"
Schedule ||--}o Action : "potentialAction"

