erDiagram
Seat {
    TextList seatNumber  
    TextList seatRow  
    TextList seatSection  
    stringList seatingType  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Seat ||--}o Action : "potentialAction"

