erDiagram
ServiceChannel {
    stringList availableLanguage  
    URLList serviceUrl  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

ServiceChannel ||--}o Duration : "processingTime"
ServiceChannel ||--}o Service : "providesService"
ServiceChannel ||--}o Place : "serviceLocation"
ServiceChannel ||--}o ContactPoint : "servicePhone"
ServiceChannel ||--}o PostalAddress : "servicePostalAddress"
ServiceChannel ||--}o ContactPoint : "serviceSmsNumber"
ServiceChannel ||--}o Action : "potentialAction"

