erDiagram
ServiceChannel {
    stringList availableLanguage  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

ServiceChannel ||--}o Duration : "processingTime"
ServiceChannel ||--}o Service : "providesService"
ServiceChannel ||--}o Place : "serviceLocation"
ServiceChannel ||--}o ContactPoint : "servicePhone"
ServiceChannel ||--}o PostalAddress : "servicePostalAddress"
ServiceChannel ||--}o ContactPoint : "serviceSmsNumber"
ServiceChannel ||--}o URL : "serviceUrl"
ServiceChannel ||--}o Text : "alternateName"
ServiceChannel ||--}o Text : "disambiguatingDescription"
ServiceChannel ||--}o Text : "name"
ServiceChannel ||--}o URL : "sameAs"
ServiceChannel ||--}o Action : "potentialAction"
ServiceChannel ||--}o URL : "url"

