erDiagram
ShippingRateSettings {
    BooleanList doesNotShip  
    stringList freeShippingThreshold  
    BooleanList isUnlabelledFallback  
    TextList shippingLabel  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

ShippingRateSettings ||--}o DefinedRegion : "shippingDestination"
ShippingRateSettings ||--}o MonetaryAmount : "shippingRate"
ShippingRateSettings ||--}o Action : "potentialAction"

