erDiagram
SizeGroupEnumeration {
    stringList supersededBy  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

SizeGroupEnumeration ||--}o Text : "alternateName"
SizeGroupEnumeration ||--}o Text : "disambiguatingDescription"
SizeGroupEnumeration ||--}o Text : "name"
SizeGroupEnumeration ||--}o URL : "sameAs"
SizeGroupEnumeration ||--}o Action : "potentialAction"
SizeGroupEnumeration ||--}o URL : "url"

