erDiagram
SizeSpecification {
    stringList sizeGroup  
    stringList sizeSystem  
    stringList suggestedGender  
    stringList valueReference  
    stringList supersededBy  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

SizeSpecification ||--}o QuantitativeValue : "hasMeasurement"
SizeSpecification ||--}o QuantitativeValue : "suggestedAge"
SizeSpecification ||--}o QuantitativeValue : "suggestedMeasurement"
SizeSpecification ||--}o PropertyValue : "additionalProperty"
SizeSpecification ||--}o QualitativeValue : "equal"
SizeSpecification ||--}o QualitativeValue : "greater"
SizeSpecification ||--}o QualitativeValue : "greaterOrEqual"
SizeSpecification ||--}o QualitativeValue : "lesser"
SizeSpecification ||--}o QualitativeValue : "lesserOrEqual"
SizeSpecification ||--}o QualitativeValue : "nonEqual"
SizeSpecification ||--}o Action : "potentialAction"

