erDiagram
SpeakableSpecification {
    CssSelectorTypeList cssSelector  
    XPathTypeList xpath  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

SpeakableSpecification ||--}o Action : "potentialAction"

