erDiagram
StatisticalVariable {
    stringList measurementMethod  
    stringList measurementTechnique  
    stringList statType  
    stringList constraintProperty  
    IntegerList numConstraints  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

StatisticalVariable ||--}o Property : "measuredProperty"
StatisticalVariable ||--}o StatisticalVariable : "measurementDenominator"
StatisticalVariable ||--}o Enumeration : "measurementQualifier"
StatisticalVariable ||--}o Class : "populationType"
StatisticalVariable ||--}o Action : "potentialAction"

