erDiagram
SubscribeAction {
    stringList location  
    stringList participant  
    stringList agent  
    stringList endTime  
    stringList provider  
    stringList startTime  
    stringList target  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

SubscribeAction ||--}o Thing : "instrument"
SubscribeAction ||--}o Thing : "object"
SubscribeAction ||--}o Thing : "result"
SubscribeAction ||--}o HowTo : "actionProcess"
SubscribeAction ||--}o ActionStatusType : "actionStatus"
SubscribeAction ||--}o Thing : "error"
SubscribeAction ||--}o Text : "alternateName"
SubscribeAction ||--}o Text : "disambiguatingDescription"
SubscribeAction ||--}o Text : "name"
SubscribeAction ||--}o URL : "sameAs"
SubscribeAction ||--}o Action : "potentialAction"
SubscribeAction ||--}o URL : "url"

