erDiagram
SuperficialAnatomy {
    TextList associatedPathophysiology  
    stringList relatedAnatomy  
    TextList significance  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

SuperficialAnatomy ||--}o MedicalCondition : "relatedCondition"
SuperficialAnatomy ||--}o MedicalTherapy : "relatedTherapy"
SuperficialAnatomy ||--}o MedicalCode : "code"
SuperficialAnatomy ||--}o Grant : "funding"
SuperficialAnatomy ||--}o MedicalGuideline : "guideline"
SuperficialAnatomy ||--}o MedicineSystem : "medicineSystem"
SuperficialAnatomy ||--}o Organization : "recognizingAuthority"
SuperficialAnatomy ||--}o MedicalSpecialty : "relevantSpecialty"
SuperficialAnatomy ||--}o MedicalStudy : "study"
SuperficialAnatomy ||--}o Action : "potentialAction"

