erDiagram
Taxon {
    stringList childTaxon  
    stringList parentTaxon  
    stringList taxonRank  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Taxon ||--}o DefinedTerm : "hasDefinedTerm"
Taxon ||--}o Action : "potentialAction"

