erDiagram
Ticket {
    stringList dateIssued  
    TextList priceCurrency  
    TextList ticketNumber  
    stringList ticketToken  
    stringList totalPrice  
    stringList underName  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Ticket ||--}o Organization : "issuedBy"
Ticket ||--}o Seat : "ticketedSeat"
Ticket ||--}o Action : "potentialAction"

