erDiagram
TipAction {
    stringList recipient  
    stringList price  
    stringList location  
    stringList participant  
    stringList agent  
    stringList endTime  
    stringList provider  
    stringList startTime  
    stringList target  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

TipAction ||--}o Text : "priceCurrency"
TipAction ||--}o PriceSpecification : "priceSpecification"
TipAction ||--}o Thing : "instrument"
TipAction ||--}o Thing : "object"
TipAction ||--}o Thing : "result"
TipAction ||--}o HowTo : "actionProcess"
TipAction ||--}o ActionStatusType : "actionStatus"
TipAction ||--}o Thing : "error"
TipAction ||--}o Text : "alternateName"
TipAction ||--}o Text : "disambiguatingDescription"
TipAction ||--}o Text : "name"
TipAction ||--}o URL : "sameAs"
TipAction ||--}o Action : "potentialAction"
TipAction ||--}o URL : "url"

