erDiagram
TrainReservation {
    stringList bookingAgent  
    DateTimeList bookingTime  
    stringList broker  
    DateTimeList modifiedTime  
    TextList priceCurrency  
    stringList provider  
    TextList reservationId  
    stringList totalPrice  
    stringList underName  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

TrainReservation ||--}o ProgramMembership : "programMembershipUsed"
TrainReservation ||--}o Thing : "reservationFor"
TrainReservation ||--}o ReservationStatusType : "reservationStatus"
TrainReservation ||--}o Ticket : "reservedTicket"
TrainReservation ||--}o Action : "potentialAction"

