erDiagram
TreatmentIndication {
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

TreatmentIndication ||--}o MedicalCode : "code"
TreatmentIndication ||--}o Grant : "funding"
TreatmentIndication ||--}o MedicalGuideline : "guideline"
TreatmentIndication ||--}o MedicineSystem : "medicineSystem"
TreatmentIndication ||--}o Organization : "recognizingAuthority"
TreatmentIndication ||--}o MedicalSpecialty : "relevantSpecialty"
TreatmentIndication ||--}o MedicalStudy : "study"
TreatmentIndication ||--}o Action : "potentialAction"

