erDiagram
TypeAndQuantityNode {
    NumberList amountOfThisGood  
    stringList typeOfGood  
    stringList unitCode  
    TextList unitText  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

TypeAndQuantityNode ||--}o BusinessFunction : "businessFunction"
TypeAndQuantityNode ||--}o Action : "potentialAction"

