erDiagram
UpdateAction {
    stringList location  
    stringList participant  
    stringList agent  
    stringList endTime  
    stringList provider  
    stringList startTime  
    stringList target  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

UpdateAction ||--}o Thing : "collection"
UpdateAction ||--}o Thing : "targetCollection"
UpdateAction ||--}o Thing : "instrument"
UpdateAction ||--}o Thing : "object"
UpdateAction ||--}o Thing : "result"
UpdateAction ||--}o HowTo : "actionProcess"
UpdateAction ||--}o ActionStatusType : "actionStatus"
UpdateAction ||--}o Thing : "error"
UpdateAction ||--}o Text : "alternateName"
UpdateAction ||--}o Text : "disambiguatingDescription"
UpdateAction ||--}o Text : "name"
UpdateAction ||--}o URL : "sameAs"
UpdateAction ||--}o Action : "potentialAction"
UpdateAction ||--}o URL : "url"

