erDiagram
Vein {
    stringList regionDrained  
    TextList associatedPathophysiology  
    TextList bodyLocation  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Vein ||--}o Vessel : "drainsTo"
Vein ||--}o AnatomicalStructure : "tributary"
Vein ||--}o AnatomicalStructure : "connectedTo"
Vein ||--}o ImageObject : "diagram"
Vein ||--}o AnatomicalSystem : "partOfSystem"
Vein ||--}o MedicalCondition : "relatedCondition"
Vein ||--}o MedicalTherapy : "relatedTherapy"
Vein ||--}o AnatomicalStructure : "subStructure"
Vein ||--}o MedicalCode : "code"
Vein ||--}o Grant : "funding"
Vein ||--}o MedicalGuideline : "guideline"
Vein ||--}o MedicineSystem : "medicineSystem"
Vein ||--}o Organization : "recognizingAuthority"
Vein ||--}o MedicalSpecialty : "relevantSpecialty"
Vein ||--}o MedicalStudy : "study"
Vein ||--}o Action : "potentialAction"

