erDiagram
Vessel {
    TextList associatedPathophysiology  
    TextList bodyLocation  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

Vessel ||--}o AnatomicalStructure : "connectedTo"
Vessel ||--}o ImageObject : "diagram"
Vessel ||--}o AnatomicalSystem : "partOfSystem"
Vessel ||--}o MedicalCondition : "relatedCondition"
Vessel ||--}o MedicalTherapy : "relatedTherapy"
Vessel ||--}o AnatomicalStructure : "subStructure"
Vessel ||--}o MedicalCode : "code"
Vessel ||--}o Grant : "funding"
Vessel ||--}o MedicalGuideline : "guideline"
Vessel ||--}o MedicineSystem : "medicineSystem"
Vessel ||--}o Organization : "recognizingAuthority"
Vessel ||--}o MedicalSpecialty : "relevantSpecialty"
Vessel ||--}o MedicalStudy : "study"
Vessel ||--}o Action : "potentialAction"

