erDiagram
VitalSign {
    stringList associatedAnatomy  
    TextList epidemiology  
    TextList expectedPrognosis  
    TextList naturalProgression  
    TextList pathophysiology  
    TextList possibleComplication  
    stringList status  
    stringList legalStatus  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

VitalSign ||--}o PhysicalExam : "identifyingExam"
VitalSign ||--}o MedicalTest : "identifyingTest"
VitalSign ||--}o MedicalTherapy : "possibleTreatment"
VitalSign ||--}o DDxElement : "differentialDiagnosis"
VitalSign ||--}o Drug : "drug"
VitalSign ||--}o MedicalTherapy : "primaryPrevention"
VitalSign ||--}o MedicalRiskFactor : "riskFactor"
VitalSign ||--}o MedicalTherapy : "secondaryPrevention"
VitalSign ||--}o MedicalSignOrSymptom : "signOrSymptom"
VitalSign ||--}o MedicalConditionStage : "stage"
VitalSign ||--}o MedicalTest : "typicalTest"
VitalSign ||--}o MedicalCode : "code"
VitalSign ||--}o Grant : "funding"
VitalSign ||--}o MedicalGuideline : "guideline"
VitalSign ||--}o MedicineSystem : "medicineSystem"
VitalSign ||--}o Organization : "recognizingAuthority"
VitalSign ||--}o MedicalSpecialty : "relevantSpecialty"
VitalSign ||--}o MedicalStudy : "study"
VitalSign ||--}o Action : "potentialAction"

