erDiagram
WarrantyPromise {
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

WarrantyPromise ||--}o QuantitativeValue : "durationOfWarranty"
WarrantyPromise ||--}o WarrantyScope : "warrantyScope"
WarrantyPromise ||--}o Action : "potentialAction"

