erDiagram
WearableMeasurementTypeEnumeration {
    stringList supersededBy  
    stringList additionalType  
    stringList description  
    stringList identifier  
    stringList image  
    stringList mainEntityOfPage  
    stringList subjectOf  
}

WearableMeasurementTypeEnumeration ||--}o Text : "alternateName"
WearableMeasurementTypeEnumeration ||--}o Text : "disambiguatingDescription"
WearableMeasurementTypeEnumeration ||--}o Text : "name"
WearableMeasurementTypeEnumeration ||--}o URL : "sameAs"
WearableMeasurementTypeEnumeration ||--}o Action : "potentialAction"
WearableMeasurementTypeEnumeration ||--}o URL : "url"

