erDiagram
WriteAction {
    stringList inLanguage  
    stringList location  
    stringList participant  
    stringList agent  
    stringList endTime  
    stringList provider  
    stringList startTime  
    stringList target  
    stringList additionalType  
    TextList alternateName  
    stringList description  
    TextList disambiguatingDescription  
    stringList identifier  
    stringList image  
    TextList name  
    URLList sameAs  
    stringList mainEntityOfPage  
    stringList subjectOf  
    URLList url  
}

WriteAction ||--}o Language : "language"
WriteAction ||--}o Thing : "instrument"
WriteAction ||--}o Thing : "object"
WriteAction ||--}o Thing : "result"
WriteAction ||--}o HowTo : "actionProcess"
WriteAction ||--}o ActionStatusType : "actionStatus"
WriteAction ||--}o Thing : "error"
WriteAction ||--}o Action : "potentialAction"

